### PR TITLE
Updates nupic.core, switches to capnp absolute imports, updates setup.py

### LINKED ISSUE #2511: Switch to capnp absolute imports to match nupic.core changes
Re https://github.com/numenta/nupic.core/issues/578

### LINKED ISSUE #2516: Random tests differ between nupic and nupic.core
Compare https://github.com/numenta/nupic/blob/master/tests/unit/nupic/math/nupic_random_test.py#L76-L77 to https://github.com/numenta/nupic.core/blob/master/src/test/unit/utils/RandomTest.cpp#L378-L379

The two tests use the same seed, but assert on different results.  This is causing tests to fail on my machine.

```
austins-mbp:nupic amarshall$ py.test tests/unit/nupic/math/nupic_random_test.py
============================================================================== test session starts ===============================================================================
platform darwin -- Python 2.7.6 -- pytest-2.4.2
plugins: cov, xdist
collected 13 items 

tests/unit/nupic/math/nupic_random_test.py .F........F..

==================================================================================== FAILURES ====================================================================================
___________________________________________________________________________ TestNupicRandom.testSample ___________________________________________________________________________

self = <tests.unit.nupic.math.nupic_random_test.TestNupicRandom testMethod=testSample>

    def testSample(self):
      r = Random(42)
      population = numpy.array([1, 2, 3, 4], dtype="uint32")
      choices = numpy.zeros([2], dtype="uint32")
    
      r.sample(population, choices)
    
>     self.assertEqual(choices[0], 2)
E     AssertionError: 1 != 2

tests/unit/nupic/math/nupic_random_test.py:76: AssertionError
__________________________________________________________________________ TestNupicRandom.testShuffle ___________________________________________________________________________

self = <tests.unit.nupic.math.nupic_random_test.TestNupicRandom testMethod=testShuffle>

    def testShuffle(self):
      r = Random(42)
      arr = numpy.array([1, 2, 3, 4], dtype="uint32")
    
      r.shuffle(arr)
    
>     self.assertEqual(arr[0], 3)
E     AssertionError: 1 != 3

tests/unit/nupic/math/nupic_random_test.py:165: AssertionError
====================================================================== 2 failed, 11 passed in 0.11 seconds =======================================================================
```

### LINKED ISSUE #2517: Travis-CI not properly testing specified nupic.core version
See https://travis-ci.org/numenta/nupic/builds/77699965, which was green.  The PR for which updates nupic.core commit to "e6bf5fd85d955ba9500ced8b011d1416856c2894" (see https://github.com/numenta/nupic/compare/core-update-e6bf5fd85d955ba9500ced8b011d1416856c2894).  However, the nupic installation downloads and installs an older version of nupic.core -- 57a614d73e65aa4fa2e7d249185069b519311b09 in this case.  See https://s3.amazonaws.com/archive.travis-ci.org/jobs/77699966/log.txt for full details.

### PR DESCRIPTION
**Pull request by scottpurdy**
Fixes #2511
Fixes #2516
Fixes #2517

- Updates to latest nupic.core SHA
- Switches to capnp absolute imports to match nupic.core changes
- Updates setup.py to treat nupic.bindings as a regular dependency
- Travis before-install scripts updated to fetch nupic.bindings based on .nupic_modules SHA
- Travis install scripts updated to pass nupic.bindings wheel dir to `pip install` via `--find-links` option
- Updates coordinate encoder test to handle non-strictly decreasing weights
- Updates misc. tests that changed due to RNG update in nupic.core
- Fixed bug in equality check in tests
- Removes dependency on pycapnp and conditioning code to skip tests if it isn't installed

### CODE REVIEW

**Comment by scottpurdy** [comment]
@oxtopus - Still in progress testing this but should be getting close. Travis fetches nupic.core in before-install scripts and passes wheel dir via `--find-links=` in the install scripts.

**Comment by rhyolight** [comment]
@scottpurdy This PR does a lot of different stuff. It's hard to write an singular issue to describe it.

**Comment by scottpurdy** [comment]
@rhyolight - I can break it up but I don't know if any of the pieces would actually pass the build. So if we want to keep it green I think it's best to keep it together. Need numenta/nupic.core#579 merged first anyway and still some things to figure out there.

**Comment by rhyolight** [comment]
Ok, I created #2511 for this.

**Pull request merged**
