### PR TITLE
Fix bug in sparse_matrix_test.py

### LINKED ISSUE #3409: Remove some bindings tests from nupic
Some rests need to be deleted to account for changes in https://github.com/numenta/nupic.core/pull/1139

The exact files that should be deleted are:

array_algorithms_test.py
cast_mode_test.py
nupic_random_test.py
sparse_binary_matrix_test.py
sparse_matrix_test.py

### PR DESCRIPTION
**Pull request by subutai**
Fixes #3409

### CODE REVIEW

**Comment by subutai** [comment]
@oxtopus

**Comment by mrcslws** [comment]
This test has been moved to nupic.core, along with other nupic.bindings tests. https://github.com/numenta/nupic.core/tree/255a76ae1bf07dcd0988e700744dc068adfa6845/bindings/py/tests

FYI I was planning on these tests from nupic after the next nupic.core release. I forgot that we'd have some failures in nupic in the meantime.

**Comment by subutai** [comment]
> FYI I was planning on removing these tests from nupic after the next nupic.core release.

Should I just delete these tests then?

**Comment by mrcslws** [comment]
Yeah, that would be good. The exact files that should be deleted are:

- array_algorithms_test.py
- cast_mode_test.py
- nupic_random_test.py
- sparse_binary_matrix_test.py
- sparse_matrix_test.py

**Comment by subutai** [comment]
Closing in favor of updated PR #3410 to delete tests.

**Pull request closed without merging**
