### PR TITLE
use cmake3 instead of cmake

### PR DESCRIPTION
**Pull request by andrewm4894**
When trying to build this dockerfile i was getting the below error:

`CMake 3.3 or higher is required. You are running version 2.8.12.2`

Using cmake3 resolves this.

### CODE REVIEW

**Comment by rhyolight** [comment]
Thanks, be sure to sign our contributor license at 
https://numenta.org/licenses/contrib/

**Comment by rhyolight** [comment]
Closing this until the OP signs our contributor license.

**Comment by andrewm4894** [comment]
Apologies, licence signed now.

**Comment by rhyolight** [comment]
@lscheinkman Any beef with this? I have not been keeping the docker config up to date. Does this affect any downstream research projects?

**Comment by lscheinkman** [comment]
@rhyolight 👍 LGTM

**Pull request closed without merging**
