### PR TITLE
Make random test cases consistent with nupic.core

### LINKED ISSUE #2516: Random tests differ between nupic and nupic.core
Compare https://github.com/numenta/nupic/blob/master/tests/unit/nupic/math/nupic_random_test.py#L76-L77 to https://github.com/numenta/nupic.core/blob/master/src/test/unit/utils/RandomTest.cpp#L378-L379

The two tests use the same seed, but assert on different results.  This is causing tests to fail on my machine.

```
austins-mbp:nupic amarshall$ py.test tests/unit/nupic/math/nupic_random_test.py
============================================================================== test session starts ===============================================================================
platform darwin -- Python 2.7.6 -- pytest-2.4.2
plugins: cov, xdist
collected 13 items 

tests/unit/nupic/math/nupic_random_test.py .F........F..

==================================================================================== FAILURES ====================================================================================
___________________________________________________________________________ TestNupicRandom.testSample ___________________________________________________________________________

self = <tests.unit.nupic.math.nupic_random_test.TestNupicRandom testMethod=testSample>

    def testSample(self):
      r = Random(42)
      population = numpy.array([1, 2, 3, 4], dtype="uint32")
      choices = numpy.zeros([2], dtype="uint32")
    
      r.sample(population, choices)
    
>     self.assertEqual(choices[0], 2)
E     AssertionError: 1 != 2

tests/unit/nupic/math/nupic_random_test.py:76: AssertionError
__________________________________________________________________________ TestNupicRandom.testShuffle ___________________________________________________________________________

self = <tests.unit.nupic.math.nupic_random_test.TestNupicRandom testMethod=testShuffle>

    def testShuffle(self):
      r = Random(42)
      arr = numpy.array([1, 2, 3, 4], dtype="uint32")
    
      r.shuffle(arr)
    
>     self.assertEqual(arr[0], 3)
E     AssertionError: 1 != 3

tests/unit/nupic/math/nupic_random_test.py:165: AssertionError
====================================================================== 2 failed, 11 passed in 0.11 seconds =======================================================================
```

### PR DESCRIPTION
**Pull request by oxtopus**
Fixes #2516

### CODE REVIEW

**Comment by scottpurdy** [comment]
:+1: if it passes

**Comment by scottpurdy** [comment]
But this may need to wait for .nupic_modules to be updated to incorporate nupic.core changes (and this change may already be part of #2489

**Comment by oxtopus** [comment]
Indeed, it is already part of #2489

**Comment by oxtopus** [comment]
Closing, since this duplicates code in pending PR #2489 (see https://github.com/numenta/nupic/pull/2489/files#diff-d0bb06bbd991282237e6994c3179467dL76)

**Pull request closed without merging**
