### PR TITLE
Changed distribution keyword, casted some attributes to float, remove…

### PR DESCRIPTION
**Pull request by kyle-sorensen**
…d setting list

### CODE REVIEW

**Comment by kyle-sorensen** [comment]
FYI this fixes broken write with capnproto on Anomalylikelihood algorithm.

**Comment by rhyolight** [comment]
@kyle-sorensen Was this reported in an issue or on the forums?

**Comment by kyle-sorensen** [comment]
@rhyolight 

#3783

Hey I just made an issue to show the obvious problem. Some of those values need to be casted to float for it to serialize.

**Comment by kyle-sorensen** [comment]
There are still some errors here.

**Pull request closed without merging**
