### PR TITLE
Removes nupic.research

### LINKED ISSUE #2569: Remove nupic/research and move algorithm code to nupic/algorithms
It is very confusing to have both nupic/research and nupic/algorithms, both of which contain algorithms. We currently import many algorithms from nupic.research instead of nupic.algorithms  It is even more confusing given that we have a nupic.research repository which is yet another thing.

This issue is to move algorithm code from nupic/research to nupic/algorithms, and to delete nupic/research altogether. As part of this we would update all tests and resolve any backward incompatibilities.

Some of the code in nupic/research, such as monitor_mixin, fdrutilities, and utils.py don't belong in nupic/algorithms and should probably move to nupic/support or some other place.

### PR DESCRIPTION
**Pull request by rhyolight**
moved contents to nupic.algorithms

fixes #2569

### CODE REVIEW

**Comment by rhyolight** [comment]
@subutai I moved all files out of `nupic.research` and into `nupic.algorithms`, and adjusted all client code to use new locations. I also renamed files according to our naming conventions, i.e `BacktrackingTMCPP` ==> `backtracking_tm_cpp`.

**Comment by subutai** [comment]
Thanks - that's great! Will look a bit later in detail. We may need to update the htmresearch repo simultaneously with this PR? htmresearch now has tests, so easier to check.

**Comment by rhyolight** [comment]
This is stalling in Travis-CI. I'm not sure why. All tests pass locally for me on OS X.

**Comment by rhyolight** [comment]
I investigated the stalled build in Travis-CI. It stalls on the test:

    tests/unit/nupic/algorithms/tm_test.py:132: TMTest.testCheckpointMiddleOfSequence2

This test does take awhile to run on my box, but the complete test suite still takes less than 10 minutes.

**Comment by rhyolight** [comment]
I think there is an issue because of these files in nupic master:

- [`tests/unit/nupic/algorithms/tm_cpp_test.py`](https://github.com/numenta/nupic/blob/a6c78976af64cfbca78f61b8f6a9cb5f1c2dd0e1/tests/unit/nupic/algorithms/tm_cpp_test.py)
- [`tests/unit/nupic/research/tm_cpp_test.py`](https://github.com/numenta/nupic/blob/a6c78976af64cfbca78f61b8f6a9cb5f1c2dd0e1/tests/unit/nupic/research/tm_cpp_test.py)

I'm not sure what `tests/unit/nupic/algorithms/tm_cpp_test.py` does. But this PR puts them together in the same module (renaming `tests/unit/nupic/algorithms/tm_cpp_test.py` ==> `tests/unit/nupic/algorithms/tm_cpp_test_2.py`). But it doesn't seem that it is running. 

Still investigating.

**Comment by scottpurdy** [comment]
@rhyolight - test files have to end in "test.py" or they aren't treated as tests. Perhaps "tm_cpp_2_test.py" for now / until someone can look into the difference between the two and how better to organize?

**Comment by rhyolight** [comment]
Thanks @scottpurdy that fixed everything. We may want to revisit the name sometime. 

Also, are you ok to merge this before https://github.com/numenta/htmresearch/pull/752?

**Pull request merged**
