### PR TITLE
Restore Connections parameter to every function in temporal memory

### PR DESCRIPTION
**Pull request by chetan51**
Fixes https://github.com/numenta/nupic/issues/2546.

### CODE REVIEW

**Comment by chetan51** [comment]
@scottpurdy

**Comment by subutai** [comment]
:+1:

**Comment by cogmission** [comment]
@rhyolight What happened to Contributor and Test coverage checks? They seem to be missing from htm.java too?

**Comment by rhyolight** [comment]
@cogmission The tooling server [crashed](http://lists.numenta.org/pipermail/nupic-hackers_lists.numenta.org/2015-September/004205.html), but it is fixed now.

**Comment by cogmission** [comment]
:+1:

**Comment by subutai** [comment]
@rhyolight Thanks!

@chetan51 I think you can merge it now. Thanks for the quick fix.

**Pull request merged**
