### PR TITLE
Removed imagesensor and related files from nupic

### LINKED ISSUE #1863: Move vision code to appropriate repo nupic.vision
and remove it from nupic. 
Relevant task: https://github.com/nupic-community/nupic.vision/issues/3

Possibly depends on https://github.com/numenta/nupic/issues/1978

### PR DESCRIPTION
**Pull request by jaredweiss**
Fixes #1863 

@scottpurdy @rhyolight Whenever you've got a chance I'd like to hear your feedback

### CODE REVIEW

**Comment by breznak** [comment]
@jaredweiss duplicate of https://github.com/numenta/nupic/pull/1866

**Comment by rhyolight** [comment]
@jaredweiss Like Marek said, there is already a PR for this at #1866. Can you review that PR, please?

**Comment by scottpurdy** [comment]
How about we mark it as deprecated now and we can delete the files in a few weeks to give people a chance to switch to nupic.vision after we clean it up.

**Comment by breznak** [comment]
I'd think we can just send a proposal (with the 2~3day no-response =
accepted limit) to the ML?

**Pull request closed without merging**
