### PR TITLE
Fix  compute Predicted Active Cells Bug in TPRegion

### PR DESCRIPTION
**Pull request by ywcui1990**
fixes https://github.com/numenta/nupic/issues/2918

@chetan51 

* Fixes compute Predicted Active cells bug in TPregion
  The predicted-active cells should be computed based on "previously" predicted cells and current active cells. 

* Remove activeCells from output. The user should use bottomUpOut instead

### CODE REVIEW

**Comment by chetan51** [comment]
:+1:

**Comment by breznak** [comment]
> By analyzing the blame information on this pull request, we identified @akhilaananthram, @scottpurdy and @chetan51 to be potential reviewers.

OT: @rhyolight is this you in disguise, or automated? The latter would be pretty cool! :eyes:

**Comment by breznak** [comment]
How serious is this change? Does it mean the "predicted cells" have been all time wrong (from TPRegion)?

**Comment by rhyolight** [comment]
> OT: @rhyolight is this you in disguise, or automated? The latter would be pretty cool!

Automated ([Facebook did it](https://github.com/facebook/mention-bot)).

**Comment by rhyolight** [comment]
@ywcui1990 Please create an issue for this to fix. Also, let me know if there is a private JIRA this should be linked to.

**Comment by rhyolight** [comment]
Fixes https://github.com/numenta/nupic/issues/2918

**Comment by rhyolight** [comment]
fixes https://github.com/numenta/nupic/issues/2918

**Comment by rhyolight** [comment]
Tooling server is no revalidating this because of https://github.com/numenta/nupic.tools/issues/219 so I'm merging.

**Comment by rhyolight** [comment]
@breznak said:
> How serious is this change? Does it mean the "predicted cells" have been all time wrong (from TPRegion)?

Can @chetan51 or @ywcui1990 answer this question?

**Comment by chetan51** [comment]
@breznak It looks like "predicted active cells" out of the `TPRegion` have been wrong until this fix.

**Comment by breznak** [comment]
> It looks like "predicted active cells" out of the TPRegion have been wrong until this fix. 

whoa! :open_mouth: anyway, good it's fixed now! :+1:

**Pull request merged**
