### PR TITLE
Correcting spatial pooler terminology to mini column instead of cortical column

### LINKED ISSUE #3259: Incorrect terminology in spatial_pooler.py
The file spatial_pooler.py contains two helper classes, CorticalColumns and BinaryCorticalColumns. These names are incorrect as these should refer to mini columns.  There are also numerous references to cortical columns in the comments.

The term "cortical column" means something completely different in neuroscience. This issue is particularly relevant since in the new theory work, we rely on the correct meaning of "cortical column".

This should be an easy change for someone to implement. Other than this file and some tests, nothing else in NuPIC uses these helper functions.

### PR DESCRIPTION
**Pull request by arhik**
Incorporated changes to the spatial terminology as mentioned which Fixes #3259.

### CODE REVIEW

**Comment by oxtopus** [comment]
👍

**Comment by rhyolight** [comment]
@scottpurdy Is this going to break our current serialization?

**Comment by scottpurdy** [comment]
@rhyolight I don't know! Not sure if we have tests covering that for this implementation.

**Comment by scottpurdy** [comment]
I can't find a test that covers it. Seems very likely that it would break the pickle serialization.

**Comment by rhyolight** [comment]
> Seems very likely that it would break the pickle serialization.

Yes, it certainly seems like it would. I guess I should not have marked #3259 as ready for work. :(

**Comment by rhyolight** [comment]
I'm sorry @arhik, but we can't merge this PR because it will change the serialization signature of the spatial pooling, which is an incompatible change with all existing versions of NuPIC. If we merged, no one would be able to de-serialize their models they saved before the change. I did not think of this when we were chatting on the original issue. This PR could be easily merged once #1450 is done. But I don't want to keep it open at this point until we're ready to merge it.

**Comment by scottpurdy** [comment]
Here is one place you can learn more about the limits of pickling (and why we will be removing it soon):
http://stackoverflow.com/questions/16269071/python-pickle-dealing-with-updated-class-definitions

**Pull request closed without merging**
