### PR TITLE
Add capnproto serialization to TPRegion

### PR DESCRIPTION
**Pull request by chetan51**
Starts on https://github.com/numenta/nupic/issues/2913.

Only works with `temporalImp='tm_py'` for now. More implementations to follow.

Depends on https://github.com/scottpurdy/nupic.core/tree/capnp-schema-library.

### CODE REVIEW

**Comment by chetan51** [comment]
@scottpurdy

**Comment by scottpurdy** [comment]
:+1:

**Comment by chetan51** [comment]
@scottpurdy I can merge after you merge https://github.com/scottpurdy/nupic.core/tree/capnp-schema-library.

**Comment by scottpurdy** [comment]
Cool, unfortunately I am pretty stumped on numenta/nupic.core#823 but hopefully I can figure it out soon.

**Comment by rhyolight** [comment]
This PR is pretty stale now.

**Pull request closed without merging**
