### PR TITLE
Remove derivated implementations of TP

### PR DESCRIPTION
**Pull request by david-ragazzi**
Fixes: #1865

### CODE REVIEW

**Comment by david-ragazzi** [comment]
Could someone review this? @chetan51 @scottpurdy @oxtopus ?

**Comment by chetan51** [comment]
Love seeing deleted code :+1:

**Comment by chetan51** [comment]
LGTM, thanks @david-ragazzi.

**Comment by david-ragazzi** [comment]
> Love seeing deleted code :+1:

Me too! :smile:

**Comment by david-ragazzi** [comment]
@rhyolight Could you merge?

**Comment by david-ragazzi** [comment]
@chetan51 Then you'll love more what https://github.com/numenta/nupic/pull/1872 will do.

**Pull request merged**
