### PR TITLE
Fixes broken TP Shim

### PR DESCRIPTION
**Pull request by chetan51**
Fixes https://github.com/numenta/nupic/issues/2277

### CODE REVIEW

**Comment by chetan51** [comment]
This fixes all prediction models, but anomaly detection models are still broken (due to a different issue).

**Comment by chetan51** [comment]
@scottpurdy

**Comment by chetan51** [comment]
cc: @marionleborgne

**Comment by scottpurdy** [comment]
Do we want to switch from a getter to direct access? Does this work for C++ version of `Connections`?

**Comment by chetan51** [comment]
@scottpurdy Good point and catch. I've updated the fix to work for both versions of `Connections`.

**Comment by chetan51** [comment]
@scottpurdy Bump

**Comment by scottpurdy** [comment]
:+1:

**Pull request merged**
