### PR TITLE
Change anomaly score to always be zero when there are no active columns.

### LINKED ISSUE #1935: Make computeRawAnomalyScore() smoother
There are 3 branches of `if` in `Anomaly.computeRawAnomalyScore()` - the core function compution anomalies. 

* the 1st branch is smooth with regards to #predicted & #active columns. 
* the branch "score = 0.0" is OK I guess
* I have a problem with the part "score = 1.0" 
https://github.com/numenta/nupic/blob/master/nupic/algorithms/anomaly.py#L47-L50 
This creates a `big` anomaly, without taking #columns into account. 
  * 0 (zero) active cols at T & 1 (out of 10.000, say) predicted col at T-1 creates the same anomaly as 
  * 0 active cols at T & 50% (out of 10.000, say) predicted cols at T-1

### PR DESCRIPTION
**Pull request by scottpurdy**
fixes #1935

### CODE REVIEW

**Comment by cogmission** [comment]
you all just make these small inconsequential changes just to keep me from catching up, right? :-)

**Comment by scottpurdy** [comment]
@cogmission - can't stop, won't stop! Perhaps release notes from each milestone would make it easier for you?

**Comment by cogmission** [comment]
Yes... Thank You!  :-)

I'm pretty far behind already, but after Net API i can work on catching up...

**Comment by breznak** [comment]
:+1:

**Comment by subutai** [comment]
:+1: This is for a very rare situation where you have no active columns at all.

**Comment by rhyolight** [comment]
@scottpurdy Please merge.

**Pull request merged**
