### PR TITLE
Sets zip_safe=False option to get pycapnp imports working

### LINKED ISSUE #2259: .capnp files not importable from egg installs
There have been a number of people having issues installing NuPIC as egg files.

### PR DESCRIPTION
**Pull request by scottpurdy**
fixes #2259 

Since the capnp schema require the ability to load files with relative paths, the zip-import functionality won't work. The `setup()` function has a `zip_safe` option that let's us specify that the archive must be unpacked when installed.

@jcasner fyi
@rhyolight please review

### CODE REVIEW

**Comment by scottpurdy** [comment]
@oxtopus - please take a look if you can

**Comment by oxtopus** [comment]
LGTM :+1:

**Comment by scottpurdy** [comment]
@rhyolight we will need another release after this is merged in order to get eggs working

**Comment by rhyolight** [comment]
@scottpurdy Sorry I missed this review request.

**Pull request merged**
