### PR TITLE
Switch over to C++ SpatialPooler where possible to speed up tests/build.

### LINKED ISSUE #2128: Switch tests/experiments to C++ SpatialPooler
NuPIC tests are running much slower since the switch to Python SpatialPooler. In general, we should use `nupic.bindings.algorithms.SpatialPooler` everywhere unless we are specifically testing the Python version. This should speed up the build/tests a lot.

Part of this change is benchmarking the tests from SHA (@rhyolight please put SHA here from before change to new SP), SHA adf01ae4 (after switch to new Python SP), and the version after switching to the new C++ version.

### PR DESCRIPTION
**Pull request by scottpurdy**
fixes #2128

### CODE REVIEW

**Comment by david-ragazzi** [comment]
Faster now (20~25 min for Linux).. I'm ignoring OS X builds because always present some problems..

**Comment by scottpurdy** [comment]
@rhyolight - Does this look like it fixes the problem to you?

**Comment by scottpurdy** [comment]
I think local timing would be more accurate than Travis.

**Comment by david-ragazzi** [comment]
> I think local timing would be more accurate than Travis.

Agreed. Travis timing depends of its queue requests.

**Comment by scottpurdy** [comment]
@chetan51 please review

**Comment by rhyolight** [comment]
> @rhyolight - Does this look like it fixes the problem to you?

Hell yes. Much, much better. :+1:

**Comment by rhyolight** [comment]
@chetan51 A quick turnaround on this review would be nice, because we are still getting build timeouts.

**Comment by chetan51** [comment]
:+1:

**Pull request merged**
