### PR TITLE
Adds basic unit test for CoordinateEncoder._hashCoordinate.

### PR DESCRIPTION
**Pull request by scottpurdy**
Addresses #2763

@chetan51 please review

### CODE REVIEW

**Comment by chetan51** [comment]
:+1:

**Comment by chetan51** [comment]
But does this actually fix the underlying issue?

**Comment by scottpurdy** [comment]
No, doesn't fix anything, just helps narrow down where the problem is.

**Comment by scottpurdy** [comment]
This doesn't seem to be a problem on any platform but still a good test to have.

**Pull request merged**
