### PR TITLE
NUP-2531: Update copyright, shorten lines to 80 chars, add Fig. 4a (overlap curve).

### PR DESCRIPTION
**Pull request by maxwellpollack**

### CODE REVIEW

**Comment by rhyolight** [comment]
Max, please sign our [contributor license](https://numenta.org/licenses/contrib/).

**Comment by maxwellpollack** [comment]
Just signed it! Thanks.

**Comment by rhyolight** [comment]
@subutai Do you want to review this or do you want me to do it?

**Comment by subutai** [comment]
> @subutai Do you want to review this or do you want me to do it?

I'll review it, thanks.

**Comment by subutai** [comment]
@rhyolight This looks good, but perhaps you want to take a quick look too? Please merge when you are ok with it - thanks!

**Pull request merged**
