### PR TITLE
Move Connections class from TemporalMemory to a separate module

### PR DESCRIPTION
**Pull request by david-ragazzi**
Fixes: https://github.com/numenta/nupic/issues/2079

### CODE REVIEW

**Comment by david-ragazzi** [comment]
@chetan51 समीक्षा करें। धन्यवाद। :smile_cat:

**Comment by breznak** [comment]
good and simple move :+1:

**Comment by david-ragazzi** [comment]
> good and simple move :+1: 

@breznak What do you think about methods renaming? Do you think is necessary, or keep `cellForSegment` term even to get a segment `column` is not confusing...

**Comment by breznak** [comment]
I think it's fine to keep for now, maybe just put a comment to SP and
Connections, that for SP: cell = column, because each column uses just 1
cell, in TP the meaning is separated as 1 col consists of more cells.

**Comment by david-ragazzi** [comment]
> I think it's fine to keep for now, maybe just put a comment to SP and
Connections, that for SP: cell = column, because each column uses just 1
cell, in TP the meaning is separated as 1 col consists of more cells.

Yeah.. I think you're right.. I update the PR, now it only move Connections from `temporal_memory.py` to a file called `connections.py`

**Comment by david-ragazzi** [comment]
@rhyolight But this PR is ready for review.. I asked to @chetan51 in hindi.. :smile:

**Comment by rhyolight** [comment]
Ok, thanks for clarifying.

**Comment by chetan51** [comment]
@david-ragazzi Obrigado!

**Comment by david-ragazzi** [comment]
> Ok, thanks for clarifying. 

आपका स्वागत है

**Comment by david-ragazzi** [comment]
> @david-ragazzi Obrigado!

Por nada!

**Pull request merged**
