### PR TITLE
Replaced hello_tp with hello_tm in docs and scripts.

### LINKED ISSUE #2660: Fix references to old "hello_tp.py" script

### PR DESCRIPTION
**Pull request by rhyolight**
Fixes #2660.

### CODE REVIEW

**Comment by rhyolight** [comment]
@numenta/nupic-reviewers simple fix for broken regression tests.

**Comment by rhyolight** [comment]
:green_apple:

**Comment by breznak** [comment]
:+1:

**Comment by rhyolight** [comment]
close enough for me!

**Comment by scottpurdy** [comment]
:+1:

**Pull request merged**
