### PR TITLE
removed redundant semicolons, fix #3408

### LINKED ISSUE #3408: Unnecessary semicolons in multiple files.
Pycharm highlighted a few unnecessary semicolons [here](https://github.com/numenta/nupic/blob/master/tests/unit/nupic/research/connections_test.py), and now I can't unsee them:

    # Let some time pass.
    connections.startNewIteration();
    connections.startNewIteration();
    connections.startNewIteration();

    # Create a segment with 3 synapse.
    segment2 = connections.createSegment(42)
    connections.createSynapse(segment2, 1, .5)
    connections.createSynapse(segment2, 2, .5)
    connections.createSynapse(segment2, 3, .5)
    connections.startNewIteration();

    # Give the first segment some activity.
    connections.recordSegmentActivity(segment1)

    # Create a new segment with 1 synapse.
    segment3 = connections.createSegment(42);
    connections.createSynapse(segment3, 1, .5)

Semicolons in python are used to write multiple function calls on the same line. Here, there's only one function per line, and python already separates functions by newlines, so the semicolons are redundant.

It technically doesn't affect anything at all... but... it irritates me slightly...

Using ctrl+shift+r in Pycharm and putting in the regex replacement ";\n" -> "\n" fixes the entire project in one go, removing what looks like 20 of those semicolons in different files. Just make sure to set file mask(s) to *.py so the *.capnp files are left alone and set context to ignore comments and string literals (though, I wonder about some of the semicolons at the ends of lines in the comments and strings too).

### PR DESCRIPTION
**Pull request by markroxor**
Pretty straightforward. Fixes #3408

### CODE REVIEW

**Comment by rhyolight** [comment]
Thank you! Please sign our [contributor license](http://numenta.org/licenses/cl/) and I will merge.

**Comment by markroxor** [comment]
Signed.

**Comment by markroxor** [comment]
ping @rhyolight

**Comment by rhyolight** [comment]
Thanks, @markroxor

**Pull request merged**
