### PR TITLE
Pattern sequence machine random impl

### LINKED ISSUE #2565: Pattern and Sequence machines shift to using nupic::Random
Currently the Pattern and Sequence machines in NuPIC use NumPy rand. This issue is to move the two machines across to use NuPIC Random.

### PR DESCRIPTION
**Pull request by rcrowder**
Fixes #2565

### CODE REVIEW

**Comment by rcrowder** [comment]
Hmmm :( As usual? the merge resolve instructions offered by Git create a new branch with rcrowder- prefix to the branch name. Is this usual? I don't seem to have needed this before? Maybe just needs a master merge.. Trying that this afternoon.

**Comment by rhyolight** [comment]
That is decidedly **un**usual for me. Very strange indeed. Not sure what is going on there. https://github.com/numenta/nupic/compare/master...rcrowder:Pattern-Sequence-Machine-Random-Impl looks like it just needs a manual merge to me. How is git suggesting a branch name?

**Comment by rcrowder** [comment]
Looks like a merge with master required. Trying that now, then trying a rebase to squash down some of these commits. This is what GH suggests I do to merge, but going to try a more usual route for me.

Step 1: From your project repository, check out a new branch and test the changes.
git checkout -b rcrowder-Pattern-Sequence-Machine-Random-Impl master
git pull https://github.com/rcrowder/nupic.git Pattern-Sequence-Machine-Random-Impl

Step 2: Merge the changes and update on GitHub.
git checkout master
git merge --no-ff rcrowder-Pattern-Sequence-Machine-Random-Impl
git push origin master

**Comment by scottpurdy** [comment]
I will rarely recommend this but for a smallish change like this and the directory structure change it will be easiest to reimplement the changes on a fresh branch.

**Comment by rcrowder** [comment]
@scottpurdy Agree. Will close this and create a fresh branch and PR.

**Pull request closed without merging**
