### PR TITLE
Installing numpy explicitly before docker build.

### LINKED ISSUE #2350: Docker builds failing since July 22 2015
https://registry.hub.docker.com/u/numenta/nupic/builds_history/15031/

/CC @allanino @oxtopus

### PR DESCRIPTION
**Pull request by rhyolight**
fixes #2350 by installing numpy in docker build instructions.

### CODE REVIEW

**Comment by rhyolight** [comment]
@oxtopus @allanino ?

**Comment by oxtopus** [comment]
Should not be necessary, but I approve.  Not related to this pr, but we need to seriously consider consolidating all of the `apt-get install` commands into a single `RUN`

**Comment by rhyolight** [comment]
dumb travis error. Not going to wait for it.

**Comment by rhyolight** [comment]
Watching https://registry.hub.docker.com/u/numenta/nupic/build_id/3974/code/bqbfs265bzzwwhzwaptca9y/ for results...

**Pull request merged**
