### PR TITLE
Move self._predictedFieldName assignment before _handleCLAClassifierMultiStep() exits

### LINKED ISSUE #1743: "Inference failed" error in Grok caused by commit ac524ac
https://github.com/numenta/nupic/commit/ac524ac384766c78786d046f50abf1907b5dd497 introduced something that started causing runtime errors in Grok. 

```
ERROR - : Inference failed for row=ModelInputRow<rowID=1, data=[datetime.datetime(2013, 12, 5, 0, 0), 5.0]>
Traceback (most recent call last):
  File "/Users/amarshall/nta/nupic/nupic/frameworks/opf/clamodel.py", line 404, in run
    inferences = self._anomalyCompute()
  File "/Users/amarshall/nta/nupic/nupic/frameworks/opf/clamodel.py", line 621, in _anomalyCompute
    inputValue=self._input[self._predictedFieldName])
KeyError: None
```

### PR DESCRIPTION
**Pull request by oxtopus**
Fixes #1743 and restores @breznak original changes.

### CODE REVIEW

**Comment by breznak** [comment]
:+1: :+1:  thanks a lot @oxtopus ! I like this one much better :wink: :beers:

**Comment by rhyolight** [comment]
:+1: Once https://github.com/numenta/nupic/pull/1742 merges.

**Comment by breznak** [comment]
> :+1: Once #1742 merges. 

@rhyolight I thought this PR is alternative to #1742 , also, that test-case commit should belong here? @oxtopus

**Comment by oxtopus** [comment]
@breznak Bear with me.  Going to get https://github.com/numenta/nupic/pull/1742 in, which reverts the original PR, and adds a test case with the necessary coverage.  Then, a separate PR will restore it along with the fix (which could be this, assuming everyone is happy with it).

**Pull request merged**
