### PR TITLE
date encoder bug fix

### LINKED ISSUE #2166: date_capnp missing
This statement fails:
```
from nupic.encoders.date_capnp import DateEncoderProto
```

### PR DESCRIPTION
**Pull request by scottpurdy**
fixes #2166 

I'm not sure how the tests pass for me without this fix...

### CODE REVIEW

**Comment by scottpurdy** [comment]
@chetan51 - please review, this is causing a failure for some people (see linked issue)

**Comment by chetan51** [comment]
:+1:

**Comment by scottpurdy** [comment]
travis appears to be hung today :(

merging and we can address if there is an issue later

**Comment by jcasner** [comment]
@rhyolight when you're back and after this is merged, can you please ship a 0.2.4 release that includes this fix?

**Comment by rhyolight** [comment]
@jcasner [0.2.4](https://github.com/numenta/nupic/releases/tag/0.2.4) will be on pypi when https://travis-ci.org/numenta/nupic/builds/68108539 passes.

**Comment by jcasner** [comment]
Thanks @rhyolight!

**Pull request merged**
