### PR TITLE
Removed topDownCompute fn from backtracking tm

### LINKED ISSUE #3646: Clean up confusing functions in BacktrackingTM
Discussion at https://discourse.numenta.org/t/backtrackingtm-topdowncompute-confusion/2352

### PR DESCRIPTION
**Pull request by rhyolight**
Fixes #3646.

### CODE REVIEW

**Comment by rhyolight** [comment]
I don't think this is going to work.

**Comment by rhyolight** [comment]
@subutai or @scottpurdy 

I'm tracing down the test failures on this one. What the heck is an `FDRTemporal`??

https://github.com/numenta/nupic/blob/master/src/nupic/regions/tm_region.py#L365

I see how `_tfdr` is created here:

https://github.com/numenta/nupic/blob/master/src/nupic/regions/tm_region.py#L420-L428

But doesn't that mean that all these implementations need to have a `topDownCompute` method because it is being called from `tm_region.py` here:

https://github.com/numenta/nupic/blob/master/src/nupic/regions/tm_region.py#L533

**Comment by subutai** [comment]
"FDR" stands for Fixed Distributed Representations which was the name for the "new theory" in 2009. It became obsolete once we switched to CLA. Oh yeah, and that is now obsolete too.  Blame Jeff, not me.

I'm pretty sure we can get rid of 'topDownMode' in this region.

**Comment by rhyolight** [comment]
Standby, a lot of trial and error involved...

**Comment by scottpurdy** [comment]
It is still pretty useful to have the "predicted columns" available. I believe that is what "topDownOut" was providing from the TM. This can be used for custom anomaly detection, reconstruction (particularly useful in image classification for debugging), and other places. So I'd like to keep this functionality but "predictedColumns" might be a better name for the region output.

**Comment by subutai** [comment]
> It is still pretty useful to have the "predicted columns" available.

Yeah.  In the research code we now have a bunch of these available as separate outputs.

https://github.com/numenta/htmresearch/blob/master/htmresearch/regions/TMRegion.py#L104

**Comment by rhyolight** [comment]
> It is still pretty useful to have the "predicted columns" available. I believe that is what "topDownOut" was providing from the TM.

It wasn't actually doing that. It was just returning the `columnConfidences`.

**Comment by rhyolight** [comment]
I'm not sure I'm going to continue with this refactoring in light of the [rabbit](https://github.com/numenta/nupic/issues/3648) [hole](https://github.com/numenta/nupic/pull/3658) I've been going down.

**Pull request closed without merging**
