### PR TITLE
Serialize data in binary format, not ascii

### PR DESCRIPTION
**Pull request by kyle-sorensen**
I understand that these methods are depreciated, but they are much faster than capnproto....with *this* change its orders of magnitude faster.

Please see: https://stackoverflow.com/questions/23582489/python-pickle-protocol-choice

**Edit: Looks like the contributor validator failed, I have already signed the paper work for this FYI, you got my fingerprints, iris scan etc**

### CODE REVIEW

**Comment by rhyolight** [comment]
Trying to make sure the tests are running properly. Failures initially on both builds.

**Comment by lscheinkman** [comment]
@kyle-sorensen The integration tests are failing. Could you please run the integration tests and make sure they pass with the new protocol? 
Here is the command to run the tests:
```
 python setup.py test --pytest-args="--verbose --boxed unit integration"
```
It looks like you need to update the tests to open the pickled files in 'binary' mode

**Comment by kyle-sorensen** [comment]
@lscheinkman I tried to run the tests as well, this is the error I get, it does not seem related to my pull request 

```
============================================================= ERRORS =============================================================
__________________________ ERROR collecting tests/unit/nupic/regions/anomaly_likelihood_region_test.py ___________________________
ImportError while importing test module '/Users/robot/nupic/tests/unit/nupic/regions/anomaly_likelihood_region_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/nupic/regions/anomaly_likelihood_region_test.py:33: in <module>
    from nupic.algorithms.anomaly_likelihood_capnp import\
E   ImportError: No module named anomaly_likelihood_capnp
```

**Comment by kyle-sorensen** [comment]
@lscheinkman Do I need a MySQL db running on localhost and 3306 to run those tests? Many of them failed on timeout errors...

`OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")`

**Comment by lscheinkman** [comment]
> @lscheinkman Do I need a MySQL db running on localhost and 3306 to run those tests? Many of them failed on timeout errors...
> 
> `OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")`

Yes, the swarm integration tests require mysql server installed.

**Comment by lscheinkman** [comment]
@kyle-sorensen The specific test failing on windows is **CheckpointStressTest::testCheckpoint** with EOFError.

I believe it is caused by opening the saved file in text mode instead of binary mode.
See https://github.com/numenta/nupic/blob/master/src/nupic/frameworks/opf/model.py#L390

**Comment by lscheinkman** [comment]
👍 LGTM

**Pull request merged**
