### PR TITLE
Fix hello_sp.py identical input test, and fix random seeds

### PR DESCRIPTION
**Pull request by chetan51**
Fixes https://github.com/numenta/nupic/issues/2840.

### CODE REVIEW

**Comment by subutai** [comment]
:+1: Thanks!

**Comment by scottpurdy** [comment]
Can we make the default the fixed seed `0`? This was discussed in numenta/nupic.core#649

**Comment by cogmission** [comment]
Can I ask how setting a different seed makes the demo not fail? Just trying to understand if I need to change something in HTM.java's SP example?

**Comment by chetan51** [comment]
@scottpurdy @cogmission Actually, the issue wasn't the seed, but rather the datatype of the input numpy arrays. I set the seed just to make this example more deterministic, but it isn't necessary to fix this issue.

**Comment by subutai** [comment]
> Can we make the default in the SP the fixed seed 0?

@scottpurdy Yes, we should do that (but in a separate PR). In CPP it is currently 1 for the SP, and in python it is currently -1.

**Pull request merged**
