### PR TITLE
Move object_json and update dependencies

### LINKED ISSUE #2430: Remove object_json dependency
The object_json.py utilities are only used within swarming so we should migrate that module into swarming

### PR DESCRIPTION
**Pull request by mihail911**
Fixes #2430 
@scottpurdy  @oxtopus

### CODE REVIEW

**Comment by oxtopus** [comment]
:+1:

**Comment by scottpurdy** [comment]
@mihail911 - update from master and resolve any conflicts
@oxtopus - pls merge when you're happy with it

**Comment by mihail911** [comment]
updated @scottpurdy  @oxtopus

**Comment by oxtopus** [comment]
:+1:

**Pull request merged**
