### PR TITLE
Removed unused tie-breaker code from SP

### LINKED ISSUE #3245: Should self._tieBreaker be removed?
It appears this is no longer used?

https://github.com/numenta/nupic/blob/master/src/nupic/research/spatial_pooler.py#L330

It used to exist in the ```inhibitColumns()```  method. Is it ok to just remove it in HTM.Java? ...or was there a substitute put in place?

### PR DESCRIPTION
**Pull request by rhyolight**
Fixes #3245.

### CODE REVIEW

**Comment by rhyolight** [comment]
Damnit my IDE keeps removing trailing whitespace without asking.

**Comment by cogmission** [comment]
One answer when Scott was making me want to cave my head in over whitespace... :-P  

[Sublime](http://www.sublimetext.com)

**Comment by rhyolight** [comment]
I have a sinking feeling about these build failures. I'm going to wait and see what https://github.com/numenta/nupic/pull/3332 does...

**Comment by rhyolight** [comment]
So the answer to this is not as easy as simply removing the code I removed.

**Comment by cogmission** [comment]
@rhyolight If the problem is in the integration "tm compatibility test" the problem likely is that the tie-breaker functionality is still getting initialized in the C++ SP here: https://github.com/numenta/nupic.core/blob/master/src/nupic/algorithms/SpatialPooler.cpp#L579

...and without that in both the Python and C++ SPs the RNG is getting out of sync and probably causing the compatibility test to fail?

**Pull request closed without merging**
