### PR TITLE
Revert "Merge pull request #1431 from breznak/anomaly_opf"

### LINKED ISSUE #1743: "Inference failed" error in Grok caused by commit ac524ac
https://github.com/numenta/nupic/commit/ac524ac384766c78786d046f50abf1907b5dd497 introduced something that started causing runtime errors in Grok. 

```
ERROR - : Inference failed for row=ModelInputRow<rowID=1, data=[datetime.datetime(2013, 12, 5, 0, 0), 5.0]>
Traceback (most recent call last):
  File "/Users/amarshall/nta/nupic/nupic/frameworks/opf/clamodel.py", line 404, in run
    inferences = self._anomalyCompute()
  File "/Users/amarshall/nta/nupic/nupic/frameworks/opf/clamodel.py", line 621, in _anomalyCompute
    inputValue=self._input[self._predictedFieldName])
KeyError: None
```

### PR DESCRIPTION
**Pull request by oxtopus**
This reverts commit ac524ac384766c78786d046f50abf1907b5dd497, reversing
changes made to ac6937b60d3e0a526cb27bd1fca253cd69ad77e1.

@scottpurdy, @rhyolight let's talk about this tomorrow.

Fixes #1743.

This reverts the broken commit and adds a unit test with coverage for the specific failure.  A proposed fix is at https://github.com/numenta/nupic/pull/1746

### CODE REVIEW

**Comment by breznak** [comment]
hmm.. :( can you share the breaking test-case, or atleast `description.py`?

**Comment by rhyolight** [comment]
@breznak Working on that, but not until tomorrow. 

Reminder: re-open https://github.com/numenta/nupic/issues/1305 when this merges.

**Comment by rhyolight** [comment]
:+1: when green.

**Pull request merged**
