### PR TITLE
Fix MANIFEST.in capnp include.

### LINKED ISSUE #2259: .capnp files not importable from egg installs
There have been a number of people having issues installing NuPIC as egg files.

### PR DESCRIPTION
**Pull request by scottpurdy**
Required for capnp files to be included in eggs.

fixes #2259 

@rhyolight please review
@jcasner @unixorn  fyi

### CODE REVIEW

**Comment by scottpurdy** [comment]
@rhyolight - I believe the egg files will need to be rebuilt after this, which probably means a version bump, right?

**Comment by rhyolight** [comment]
@scottpurdy Yes, if you want to get the egg from https://pypi.python.org/pypi/nupic. We don't publish eggs anywhere else.

**Comment by scottpurdy** [comment]
@rhyolight please review

**Comment by rhyolight** [comment]
@scottpurdy No, I have [a release script](https://github.com/rhyolight/nupic.devtools/blob/master/bin/release) that does all that. Just tell me when it's merged and I can run it any time (anyone with push access and the properly API credentials set can run it).

**Comment by scottpurdy** [comment]
@rhyolight - Can you review / give this a thumbs up?

**Comment by rhyolight** [comment]
:+1:

**Pull request merged**
