### PR TITLE
Remove $NUPIC dependency

### LINKED ISSUE #1947: Swarming returns JSON error when NUPIC environment variable is unset
To replicate:

1. install nupic from source following README instructions
1. `cd examples/opf/clients/hotgym/prediction/one_gym`
1. `unset NUPIC` (if set)
1. `python swarm.py`

Error:

```
∙ ./swarm.py
This script runs a swarm on the input data (rec-center-hourly.csv) and
creates a model parameters file in the `model_params` directory containing
the best model found by the swarm. Dumps a bunch of crud to stdout because
that is just what swarming does at this point. You really don't need to
pay any attention to it.

=================================================
= Swarming on rec-center-hourly data...
= Medium swarm. Sit back and relax, this could take awhile.
=================================================
Generating experiment files in directory: /Users/mtaylor/nta/nupic/examples/opf/clients/hotgym/prediction/one_gym/swarm...
Writing  313 lines...
Writing  113 lines...
done.
None
Successfully submitted new HyperSearch job, jobID=1411
Evaluated 0 models
HyperSearch finished!
Worker completion message: None

Results from all experiments:
----------------------------------------------------------------
Generating experiment files in directory: /var/folders/c1/fc9tt93s2p5b9d3wp185qxwc0000gn/T/tmp6234aw...
Writing  313 lines...
Writing  113 lines...
done.
None
json.loads(jobInfo.results) raised an exception.  Here is some info to help with debugging:
jobInfo:  _jobInfoNamedTuple(jobId=1411, client=u'GRP', clientInfo=u'', clientKey=u'', cmdLine=u'$HYPERSEARCH', params=u'{"hsVersion": "v2", "maxModels": null, "persistentJobGUID": "0d6edaa1-d262-11e4-94c6-600308a99116", "useTerminators": false, "description": {"includedFields": [{"fieldName": "timestamp", "fieldType": "datetime"}, {"maxValue": 53.0, "fieldName": "kw_energy_consumption", "fieldType": "float", "minValue": 0.0}], "streamDef": {"info": "kw_energy_consumption", "version": 1, "streams": [{"info": "Rec Center", "source": "file://rec-center-hourly.csv", "columns": ["*"]}]}, "inferenceType": "TemporalMultiStep", "inferenceArgs": {"predictionSteps": [1], "predictedField": "kw_energy_consumption"}, "iterationCount": -1, "swarmSize": "medium"}}', jobHash='\ro\x9b\xd4\xd2b\x11\xe4\xa0\xfa`\x03\x08\xa9\x91\x16', status=u'notStarted', completionReason=None, completionMsg=None, workerCompletionReason=u'success', workerCompletionMsg=None, cancel=0, startTime=None, endTime=None, results=None, engJobType=u'hypersearch', minimumWorkers=1, maximumWorkers=4, priority=0, engAllocateNewWorkers=1, engUntendedDeadWorkers=0, numFailedWorkers=0, lastFailedWorkerErrorMsg=None, engCleaningStatus=u'notdone', genBaseDescription=None, genPermutations=None, engLastUpdateTime=datetime.datetime(2015, 3, 24, 20, 12, 10), engCjmConnId=None, engWorkerState=None, engStatus=None, engModelMilestones=None)
jobInfo.results:  None
EXCEPTION:  expected string or buffer
Traceback (most recent call last):
  File "./swarm.py", line 109, in <module>
    swarm(INPUT_FILE)
  File "./swarm.py", line 101, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "./swarm.py", line 78, in swarmForBestModelParams
    verbosity=0
  File "/Users/mtaylor/nta/nupic/nupic/swarming/permutations_runner.py", line 276, in runWithConfig
    return _runAction(runOptions)
  File "/Users/mtaylor/nta/nupic/nupic/swarming/permutations_runner.py", line 217, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/Users/mtaylor/nta/nupic/nupic/swarming/permutations_runner.py", line 160, in _runHyperSearch
    metricsKeys=search.getDiscoveredMetricsKeys())
  File "/Users/mtaylor/nta/nupic/nupic/swarming/permutations_runner.py", line 825, in generateReport
    results = json.loads(jobInfo.results)
  File "/Users/mtaylor/nta/nupic/nupic/support/object_json.py", line 163, in loads
    json.loads(s, object_hook=objectDecoderHook, **kwargs))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

CC @pehlert

### PR DESCRIPTION
**Pull request by passiweinberger**
had an issue with the NUPIC variable, heared you were about to remove them anyways, so I just did it :) Hope this helps :)

fixes #1947

### CODE REVIEW

**Comment by rhyolight** [comment]
Thanks, @passiweinberger. I will try to test this out Monday.

**Comment by rhyolight** [comment]
Although this fixes tests, not sure it fixes the general swarming problem.

**Comment by passiweinberger** [comment]
Yes. True, I'll get my hand on it 2day. Sorry don't merge yet

<div>-------- Original message --------</div><div>From: Matthew Taylor <notifications@github.com> </div><div>Date:03/30/2015  03:48  (GMT+01:00) </div><div>To: numenta/nupic <nupic@noreply.github.com> </div><div>Cc: Pascal Weinberger <passiweinberger@gmail.com> </div><div>Subject: Re: [nupic] Remove $NUPIC dependency (#1968) </div><div>
</div>Although this fixes tests, not sure it fixes the general swarming problem.

**Comment by passiweinberger** [comment]
But wanted to make sure this way to fix it is acceptable :)

**Comment by pehlert** [comment]
I had a go at removing all $NUPIC dependencies, too. Saw too late, that @passiweinberger was working on it. It's surely a more controversial approach and I'm not sure if that's in line with Python best practices, but please have a look: https://github.com/numenta/nupic/pull/1970

**Comment by passiweinberger** [comment]
@pehlert s fix works. Close this one, no need for dublicates :D

**Comment by passiweinberger** [comment]
Now it removes the NUPIC path completely as suggested by @david-ragazzi in #1970 if we decide to do it :)

**Comment by david-ragazzi** [comment]
HI @passiweinberger , I think it's better we keep a single PR for this issue. :-/ So how about push my suggestion (https://github.com/numenta/nupic/pull/1970/files#r27405407) into @pehlert . This way we centralize efforts.. :-)

**Comment by passiweinberger** [comment]
(Y)

**Comment by rhyolight** [comment]
Seems to me like https://github.com/numenta/nupic/pull/1970 should be merged first, and then this PR should be updated to use `NUPIC_ROOT`?

**Comment by rhyolight** [comment]
blocked by https://github.com/numenta/nupic/pull/1970

**Comment by passiweinberger** [comment]
#2205

**Pull request closed without merging**
