### PR TITLE
fix likelihood default timestamp - use iteration step

### PR DESCRIPTION
**Pull request by breznak**
instead of datetime.now() for equality of 2 likelihood instances
called with same numbers withnout timestamps.

Fixes: #2260

### CODE REVIEW

**Comment by breznak** [comment]
@rhyolight please merge

**Comment by rhyolight** [comment]
Before merging, I want @scottpurdy or @subutai to give their opinion. I may be wrong.

**Comment by scottpurdy** [comment]
Seems reasonable but I'll defer to @subutai in case he knows why we had it default to the current time.

**Comment by breznak** [comment]
> That was done for convenience when you can't/don't want to pass the timestamp manually.  

When I added the functionality to call likelihood from Anomaly class, some records wouldn't pass timestamp, instead pass None, so we added this work-around.

**Comment by rhyolight** [comment]
@subutai Your opinion is requested above.

**Pull request merged**
