### PR TITLE
Extended logger

### LINKED ISSUE #2426: Resolve Swarming ExtendedLogger Dependency On NuPIC
Move ExtendedLogger module from outside swarming into swarming, since the rest of NuPIC has no dependency on ExtendedLogger.

### PR DESCRIPTION
**Pull request by mihail911**
Fixes #2426 
@scottpurdy @oxtopus

### CODE REVIEW

**Comment by oxtopus** [comment]
:+1:

**Comment by scottpurdy** [comment]
@mihail911 this also needs to be updated

**Comment by mihail911** [comment]
updated @scottpurdy @oxtopus

**Comment by oxtopus** [comment]
:+1:

**Pull request merged**
