### PR TITLE
Adding dependency listing with licenses.

### LINKED ISSUE #2010: Create top-level file that maps all dependencies and their licenses
This was suggested by our lawyer. I like to take our lawyer's suggestions. :wink:

### PR DESCRIPTION
**Pull request by rhyolight**
Fixes #2010

### CODE REVIEW

**Comment by rhyolight** [comment]
@scottpurdy

**Comment by scottpurdy** [comment]
What does it mean when you don't specify what the license type is? Custom license? Is it permissive?

**Comment by rhyolight** [comment]
All the unspecified licenses are permission, usually derivations of MIT.
But if it doesn't explicitly list the license, I didn't use it in the
license name.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by scottpurdy** [comment]
I'd suggest that we:

1. Link to the nupic.core dependency file rather than relist them and try to keep them in sync.
2. Alphabetize each section.

**Comment by scottpurdy** [comment]
:+1: with out without the suggestions

**Comment by rhyolight** [comment]
> Alphabetize each section.

Definitely.

> Link to the nupic.core dependency file rather than relist them and try to keep them in sync.

Not sure about this. I made the decision about what was on this list based on either defined pip dependencies in `requirements.txt` or C source code within this repository. I don't want to leave any out even if they are also required by `nupic.core`.

**Comment by scottpurdy** [comment]
> I made the decision about what was on this list based on either defined pip dependencies in requirements.txt or C source code within this repository. I don't want to leave any out even if they are also required by nupic.core.

Ahh, I thought you were listing dependencies that were in nupic.core and only implicitly included by the dependence on nupic.core. But if the dependency is in this repo directly then I definitely agree.

**Comment by scottpurdy** [comment]
:+1:

**Pull request merged**
