### PR TITLE
correct test implementation to close issue #1831

### LINKED ISSUE #1831: anomaly_likelihood_test: Has Broken Test (Fix is in comment)
## The text below contains both the description of the problem, and the fix to make the test work, and the code improvement of the class being tested.
 
**.../nupic/tests/unit/nupic/algorithms/anomaly_likelihood_test.py line#226**
testEstimateAnomalyLikelihoodsMalformedRecords() - ***actually tests nothing.***

#### the lines:

data1 = _generateSampleData(mean=0.2)
data1 = data1 + [(2, 2), (2, 2, 2, 2), (), (2)]  # Malformed records
    
likelihoods, avgRecordList, estimatorParams = (
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;an.estimateAnomalyLikelihoods(data1[0:1000])
)

#### should be changed to:

data1 = _generateSampleData(mean=0.2)
data1 = data1**[0:996]** + [(2, 2), (2, 2, 2, 2), (), (2)]  # Malformed records
    
likelihoods, avgRecordList, estimatorParams = (
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;an.estimateAnomalyLikelihoods(data1[0:1000])
)

... so that when estimateAnomalyLikelihoods() is called with **data1[0:1000]** , the "malformed" records will be included.

##### A corresponding change is needed in anomaly_likelihood.py in order to have the 2nd to last record not cause an exception (i.e. the "()" in  [(2, 2), (2, 2, 2, 2), (), (2)]). 

_This is so because the test method as previously written never actually passed the above malformed records in to the method being tested; now that they are being passed in, the code which "detects" bad records is now being executed._

**The required change is on line#486 in the _anomalyScoreMovingAverage() method:**

#### Instead of:
if len(record) != 3:
&nbsp;&nbsp;&nbsp;if verbosity >= 0:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print "Malformed record:", record
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue

#### Should be:
if **not isinstance(record, list) or** len(record) != 3:
&nbsp;&nbsp;&nbsp;if verbosity >= 0:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print "Malformed record:", record
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue

### PR DESCRIPTION
**Pull request by BoltzmannBrain**
@rhyolight @cogmission this closes fixes #1831; see an explanation in my comment there.

### CODE REVIEW

**Comment by rhyolight** [comment]
:+1:

**Comment by cogmission** [comment]
omg! what a screwey language!  :-P   Oh well, learn something new everyday!

**Comment by BoltzmannBrain** [comment]
@rhyolight please merge, I don't have write access.

**Comment by cogmission** [comment]
:+1:  @BoltzmannBrain Good job and good eye, ferreting that out btw! I'm sorry but Python kind of annoys me - but I'm glad you had the eye to catch this!

**Comment by rhyolight** [comment]
@cogmission IMO your contention is more with dynamic typing than Python itself.

**Comment by cogmission** [comment]
@rhyolight You're probably right. Because I like all the operations you can
do on lists and how easily you can manipulate things with very little
syntax overhead. Dynamic Typing is the devil though... IMO

On Fri, Mar 6, 2015 at 2:13 PM, Matthew Taylor <notifications@github.com>
wrote:

> @cogmission <https://github.com/cogmission> IMO your contention is more
> with dynamic typing than Python itself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/pull/1916#issuecomment-77627285>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by rhyolight** [comment]
tumblr_n4g7ifroct1t5bluao1_500

**Comment by cogmission** [comment]
LOL!!!!!  :-)

On Fri, Mar 6, 2015 at 2:38 PM, Matthew Taylor <notifications@github.com>
wrote:

> [image: tumblr_n4g7ifroct1t5bluao1_500]
> <https://cloud.githubusercontent.com/assets/15566/6535908/ae46186e-c3fd-11e4-854f-37045688d1cd.gif>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/pull/1916#issuecomment-77631273>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Pull request merged**
