### PR TITLE
fix for bug #2265

### PR DESCRIPTION
**Pull request by go-bears**
Fixes http://github.com/numenta/nupic/issues/2265

@oxtopus
I added the .py extension to the filename; does this resolve the issue?

### CODE REVIEW

**Comment by rhyolight** [comment]
There is a change needed in our continuous integration scripts as well. That is why the builds are failing at https://travis-ci.org/numenta/nupic/builds/82501282. See:

```
ci/travis/script-run-tests.sh
28:${TRAVIS_BUILD_DIR}/scripts/run_nupic_tests -u --coverage --failfast || exit
32:${TRAVIS_BUILD_DIR}/scripts/run_nupic_tests -i --coverage --failfast || exit
```

**Comment by rhyolight** [comment]
Another note, there are areas of the wiki that refer to this script as well:

- https://github.com/numenta/nupic/wiki/Install-NuPIC-using-Docker
- https://github.com/numenta/nupic/wiki/Installing-and-Building-NuPIC

**Comment by oxtopus** [comment]
Yes, it should resolve the issue, but needs a passing build and updated documentation before it can be merged.  Thanks!

**Comment by go-bears** [comment]
I can edit the documentation on the wiki to reflect the file name changes. Thanks for looking into this!

**Comment by rhyolight** [comment]
Sure thing, but don't edit it until this PR is merged. Can you also make the necessary changes to `ci/travis/script-run-tests.sh`?

**Comment by go-bears** [comment]
I can try to move on to fixing the references in documentation?

**Comment by rhyolight** [comment]
@go-bears Yes, I just merged this PR, so go for it! 

Thank you for your contribution! 

africanamerican_girl_thumbs_up23

**Comment by go-bears** [comment]
@ rhyolight 

Thanks, just changed the documentation references on the wiki.  Thanks!

**Pull request merged**
