### PR TITLE
Appveyor setup

### LINKED ISSUE #1785: Add Appveyor integration to NuPIC build pipeline
Once Windows builds are supported and passing in Appveyor, our CI pipeline needs to be updated to integrate Appveyor services in the same fashion as Travis-CI

* * *

- [x] `nupic.core` pull requests are validated with Appveyor build results
- [x] [Appveyor runs on push to nupic.core master](https://github.com/numenta/nupic.core/issues/210)
- [ ] [Appveyor runs on push to nupic master](https://github.com/numenta/nupic/issues/1784)
- [ ] NuPIC pull requests are validated with Appveyor build results
- [X] NuPIC Status Board reports on running Appveyor builds (`nupic.core`)
- [ ] NuPIC Status Board reports on running Appveyor builds (`nupic`)
- [x] Update README with numenta/nupic.core appveyor status. The current status link (https://ci.appveyor.com/api/projects/status/g2vdotgyeh8nnpnn) is pointing to @rcrowder branch.
- [x] Include appveyor build status into `check list` for PRs.

### PR DESCRIPTION
**Pull request by rcrowder**
Fixes #1785 Initial work to integrate AppVeyor into NuPIC

### CODE REVIEW

**Comment by scottpurdy** [comment]
Let's not wait until all the tests are passing to get this stuff merged. We can follow up to fix the remaining tests.

**Comment by rcrowder** [comment]
@scottpurdy kk @rhyolight We need nupic on appveyor enabling to test this.
This is mainly blocked by the pycapnp dependency in the nupic.core/bindings/py/requirements.txt file.  Results in a wheel install fail that's likely to fail an AV build. Along with the current failing tests.

**Comment by rhyolight** [comment]
@rcrowder https://ci.appveyor.com/project/numenta-ci/nupic

**Comment by rcrowder** [comment]
@rhyolight Many thanks. Could you quickly sort this questions out too?
https://github.com/numenta/numenta.org/issues/234#issuecomment-153511167

**Comment by rhyolight** [comment]
done

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by rcrowder** [comment]
Thanks :) Now just need to work out why S3 upload on AV is failing for the bindings :(

**Comment by rhyolight** [comment]
What is the error?

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by rcrowder** [comment]
I know when it started to occur. No error apart from 'Access denied' in the AV logs, so will narrow down why it occurs (and try out boto and the Travis Python upload scripts as replacement for AV deployment). AV does some odd things running the YAML that has caught me out a few times. Moving more away to known working procedures and scripting, away from some 'blackbox' processing.

**Pull request merged**
