### PR TITLE
Sparse map potential

### LINKED ISSUE #1385: The _mapPotential method and the SparseBinaryArray, return a dense array
_mapPotential is called from the bottom of the  __init__ method where there is a loop which iterates over columns and initializes the assignment of the potentialPool (collection of input bits each column is associated with). The first line of the loop calls _mapPotential which returns a binary array of ones and zeroes (ones in the places indicating the index of the input vector's bits a given column has in its "pool", zeros in the places indicating the indexes of bits unconnected).

This return value should simply be an array of the actual indexes, resulting in a much shorter array.
(for example:  [1,2,4] instead of [0,1,1,0,1])

Loop over 2048 columns--
**Iteration 1**
The reason for this is that this array is then passed to _potentialPools.replaceSparseRow() calling             [].nonzero()[0]. This internally iterates over the indexes in the array and returns [1,2,4], sticking with our example. In the normal case, this is an array of 2048 items, keep in mind. 

**Iteration 2**
The updatePermanencesForColumn() method is then called which in the first line calls:
maskPotential = numpy.where(self._potentialPools.getRow(index) > 0)[0] in order to obtain the array [1,2,4].
self._potentialPools.getRow(index) returns a "dense" array ([0,1,1,0,1]) which numpy must iterate over to extract the indexes of nonzero items seen above. This amounts to 2048 \* 2048.

All of the above iteration would not be needed if _mapPotential returned a "sparse" array and self._potentialPools returned the sparse array ([1,2,4]) instead of the dense array (0,1,1,0,1]).

Again, there would be absolutely no iteration if the above were fixed.

### PR DESCRIPTION
**Pull request by breznak**
makes SP mapPotential() return a sparse array of active indices. 
python part.
Blocked by: https://github.com/numenta/nupic.core/pull/285
Fixes #1385

### CODE REVIEW

**Comment by cogmission** [comment]
Did this get lost? :)

**Comment by rhyolight** [comment]
@breznak works in spurts :wink:

**Comment by rhyolight** [comment]
@breznak ping

**Comment by breznak** [comment]
@rhyolight pong .. :disappointed: I sometimes try I bit in this PR, not no real progress.. Still ready for adoption from someone.

**Comment by cogmission** [comment]
What's the status? Is this waiting for a correlated change in nupic.core?

On Sat, Feb 28, 2015 at 4:22 PM, breznak <notifications@github.com> wrote:

> @rhyolight <https://github.com/rhyolight> pong .. [image: :disappointed:]
> I sometimes try I bit in this PR, not no real progress.. Still ready for
> adoption from someone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/pull/1416#issuecomment-76551669>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by rhyolight** [comment]
@cogmission No, the nupic.core change is https://github.com/numenta/nupic.core/pull/285 but there is a test failure when running them together. @breznak has worked on fixing the test failure, but is having troubles figuring it out.

**Comment by breznak** [comment]
closing, no time..

**Comment by cogmission** [comment]
What possible reason could we have for ignoring this? This is a eye-sore /
very obvious inefficiency? Are we just going to send it off into the ether
and forget about it? :-P

On Tue, May 19, 2015 at 12:25 PM, breznak <notifications@github.com> wrote:

> Closed #1416 <https://github.com/numenta/nupic/pull/1416>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/pull/1416#event-308710342>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by breznak** [comment]
well.. I like the idea and solution behind this issue - which you figured
and proposed, i tried to forge some implementation, but there is some bug
which I did not crack.
I'm closing this under Matt's (imho reasonable) proposal on ML about old
PRs - I don't have time to work on this now and, as stated somewhere
before, if the Connections kick in for SP - this issue would be obsoleted
anyway. The issue still stays open, so anyone can take this code and work
off that..

**Pull request closed without merging**
