### PR TITLE
Fix: When coordinate encoder is used with DateEncoder, ValueError occurs

### PR DESCRIPTION
**Pull request by chetan51**
Fixes https://github.com/numenta/nupic/issues/1798.

### CODE REVIEW

**Comment by chetan51** [comment]
@rhyolight

**Comment by rhyolight** [comment]
Now I'm getting this error:

    ValueError: could not broadcast input array from shape (4) into shape (5)

Used to be:

    ValueError: could not broadcast input array from shape (2) into shape (4)

**Comment by chetan51** [comment]
@rhyolight This is with the timestamp enabled, right? Does it work without the timestamp enabled?

**Comment by rhyolight** [comment]
@chetan51 Yes, with timestamp enabled.

**Comment by rhyolight** [comment]
> Does it work without the timestamp enabled?

Let me check.

**Comment by rhyolight** [comment]
@chetan51 Two different errors:

### With timestamp enabled:

```
> python run.py output/sample.csv -t
...
Traceback (most recent call last):
  File "run.py", line 110, in <module>
    not options.manualSequence)
  File "run.py", line 89, in run
    useTimeEncoders=useTimeEncoders)
  File "/Users/mtaylor/nta/nupic.geospatial/model/geospatial_anomaly.py", line 121, in runGeospatialAnomaly
    result = model.run(modelInput)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/frameworks/opf/clamodel.py", line 381, in run
    self._sensorCompute(inputRecord)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/frameworks/opf/clamodel.py", line 449, in _sensorCompute
    sensor.compute()
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/engine/__init__.py", line 443, in compute
    return self._region.compute()
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/bindings/engine_internal.py", line 1299, in compute
    return _engine_internal.Region_compute(self)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/regions/RecordSensor.py", line 296, in compute
    outputs['sourceOut'][:] = self.encoder.getScalars(data)
ValueError: could not broadcast input array from shape (4) into shape (5)
```

### No timestamp enabled:

```
> python run.py output/sample.csv
...
Traceback (most recent call last):
  File "run.py", line 110, in <module>
    not options.manualSequence)
  File "run.py", line 89, in run
    useTimeEncoders=useTimeEncoders)
  File "/Users/mtaylor/nta/nupic.geospatial/model/geospatial_anomaly.py", line 121, in runGeospatialAnomaly
    result = model.run(modelInput)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/frameworks/opf/clamodel.py", line 381, in run
    self._sensorCompute(inputRecord)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/frameworks/opf/clamodel.py", line 449, in _sensorCompute
    sensor.compute()
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/engine/__init__.py", line 443, in compute
    return self._region.compute()
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/bindings/engine_internal.py", line 1299, in compute
    return _engine_internal.Region_compute(self)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/regions/RecordSensor.py", line 296, in compute
    outputs['sourceOut'][:] = self.encoder.getScalars(data)
ValueError: could not broadcast input array from shape (3) into shape (4)
```

**Comment by chetan51** [comment]
That's weird, I don't see that. Can you post `sample.csv`?

**Comment by rhyolight** [comment]
https://gist.github.com/rhyolight/c5917f20bb222e37bc0c

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by chetan51** [comment]
That's odd, that's not what I see running the same `sample.csv`. For me it works fine, with or without timestamp. Do you have the latest version of nupic and nupic.geospatial, and with this PR's branch checked out?

**Comment by rhyolight** [comment]
My fault, it works! I think I was was on a bad nupic.geospatial SHA.

**Pull request merged**
