### PR TITLE
Change default value of predictedSegmentDecrement to 0

### PR DESCRIPTION
**Pull request by ywcui1990**
Fixes https://github.com/numenta/nupic/issues/2307

@chetan51

### CODE REVIEW

**Comment by chetan51** [comment]
:+1:

**Comment by ywcui1990** [comment]
@chetan51 Please merge. I don't have write access to nupic.

**Comment by chetan51** [comment]
Will do after the build passes.

**Comment by ywcui1990** [comment]
@chetan51 Please merge.

**Pull request merged**
