### PR TITLE
Fix Boosting bump up weak columns period

### PR DESCRIPTION
**Pull request by breznak**
Fixes: #2646 
"blocked" by: #2620 (builds on it)

### CODE REVIEW

**Comment by breznak** [comment]
Here is a view for better review: 
https://github.com/breznak/nupic/compare/boosting...breznak:boosting_bumpUpWeak_fix?expand=1

**Comment by rhyolight** [comment]
@breznak Maybe I missed some discussion about this, but I'm concerned that you wrote a lot of new code for this PR before we had much discussion about it. I'm not sure what other @numenta/nupic-committers  think about this change...

**Comment by rhyolight** [comment]
@breznak Ah wait, never mind. I see that this PR builds on top of https://github.com/numenta/nupic/pull/2620.

**Comment by breznak** [comment]
Closing this as I will leave it for my "alternative boosting implementation".

**Pull request closed without merging**
