### PR TITLE
Expanding ~ to user's home directory

### LINKED ISSUE #1925: specifying --nupic-core-dir= with a relative path breaks the build
The message is quite cryptic, either we should 
* throw an error that the path must be absolute
* translate relative path correctly

When:
* building nupic with custom `core` location

Steps to reproduce:
`python setup.py --nupic-core-dir=~/nupic.core/build/release build` 
fails, while `python setup.py --nupic-core-dir=/home/user/nupic.core/build/release build` is OK.

### PR DESCRIPTION
**Pull request by rhyolight**
... if included in core path.

Fixes #1925.

### CODE REVIEW

**Comment by rhyolight** [comment]
@breznak This should work.

**Comment by breznak** [comment]
cool :+1:

**Comment by breznak** [comment]
https://travis-ci.org/numenta/nupic/jobs/56975339#L395
I think you must handle case where no path is given (None) @rhyolight

**Comment by rhyolight** [comment]
I'm one step ahead of you :runner:

**Comment by breznak** [comment]
..you are faster than my connection today! :cookie:

**Comment by breznak** [comment]
...again :grinning:

**Pull request merged**
