### PR TITLE
Removed FastTemporalMemory from nupic

### LINKED ISSUE #2996: Remove fast_temporal_memory
Once C++ TemporalMemory is tested and working, remove fast_temporal_memory and all its remnants (including shims, monitoring, example code, etc.) from NuPIC.

### PR DESCRIPTION
**Pull request by SaganBolliger**
Deleted fast_temporal_memory.py
Removed references from TPRegion.py, TP_shim.py, and hello_tm.py

These are all the remnants of FastTemporalMemory I could find.

Fixes #2996

### CODE REVIEW

**Comment by SaganBolliger** [comment]
@chetan51 Please review.

**Comment by chetan51** [comment]
:+1: But let's finish the other tasks in https://github.com/numenta/nupic/issues/2949 before merging.

**Comment by subutai** [comment]
@chetan51 @SaganBolliger @scottpurdy I don't know that this should be blocked on the other issues. We are not using this class, don't have plans to use this class, and the other issues are not testing this class.  So why not merge it and be done with it?

**Comment by chetan51** [comment]
@subutai You're right, merged!

**Pull request merged**
