### PR TITLE
Added links to installation videos.

### LINKED ISSUE #2599: Add video installation guides to README
Hey @numenta/nupic-committers, do you think the README is an appropriate place to put links to video installation guides like this:

[Installing NuPIC on Ubuntu Video Thumbnail](http://www.youtube.com/watch?v=1fIpgXHXAZA)

### PR DESCRIPTION
**Pull request by rhyolight**
Fixes #2599.

### CODE REVIEW

**Comment by rhyolight** [comment]
I decided to leave the images out. They seemed like gaudy overkill for a README. 

@numenta/nupic-reviewers Please review.

**Comment by vitaly-krugl** [comment]
@rhyolight: the OS X nupic installation video is frustrating to watch due to the many mistakes.

**Comment by rhyolight** [comment]
@vitaly-krugl Running into the mistakes was actually intentional (for the most part). I wanted to show what errors typically occurred when users tried to install, and then show the workaround for that error. All the errors I ran into are errors that users have reported in the past. Showing how they occur and how to work around them was an objective of mine. The only error I unintentionally made was installing `py.test` with `sudo`. 

However, it does make for a much less-polished video, so maybe they should not be linked from the README.

**Comment by vitaly-krugl** [comment]
In the ubuntu video: 

* there is a section in the beginning about 25 seconds long, where I think Ubuntu is performing some sort of validation; it would be nice to speed that up.

**Comment by rhyolight** [comment]
How far along in the video does this occur? I sped it up in several places already, but my editing software sometimes does not apply these types of transformations properly.

**Comment by vitaly-krugl** [comment]
In https://www.youtube.com/watch?v=1fIpgXHXAZA, the unnecessary delay occurred starting at about 0:12, but it looks like it's been sped it up since I saw it, so it's okay now.

**Comment by rhyolight** [comment]
What does everyone else think? Should these binary installation videos be
linked from the main README or only in the wiki at
https://github.com/numenta/nupic/wiki/Installing-and-Building-NuPIC ?

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by vitaly-krugl** [comment]
What I think helped make the Ubuntu video more palatable is that you explicitly explain why you will be making the mistakes here https://youtu.be/1fIpgXHXAZA?t=80

**Comment by rhyolight** [comment]
@vitaly-krugl Thanks for your feedback, Vitaly. I admit that these videos were a bit rushed, because I wanted to get them out there for HTM Challenge users before they ran into problems and turned away in frustration.

**Pull request closed without merging**
