### PR TITLE
Removes isDelta method from encoder base class.

### LINKED ISSUE #1829: Remove delta encoder special casing
The CLAModel has special casing for delta encoders that enable the delta encoder to be the predicted field, where the delta is fed to the model but the classifier predicts the actual, non-delta, future value. I'm not sure this is a real use-case so wanted to open an issue for discussion. The delta encoder makes sense as an auxiliary field, similar to the various ways to encode dates, but not as a way to predict the original values.

If this isn't a real use case then we can clean up a lot of special-casing code in the encoder base class and the CLAModel.

@subutai - can you comment on this?

### PR DESCRIPTION
**Pull request by scottpurdy**
CLAModel now uses `isinstance(encoder, DeltaEncoder)` to special case the delta encoder.

@subutai please review

fixes #1829

### CODE REVIEW

**Comment by breznak** [comment]
:+1:

**Comment by rhyolight** [comment]
Ignore the coveralls failure. I don't know when they decided to start using the status API.

**Comment by cogmission** [comment]
Saturday or Sunday apparently... :(  Got me too!

**Comment by rhyolight** [comment]
:+1:

**Comment by scottpurdy** [comment]
@chetan51 - please review

**Comment by chetan51** [comment]
:+1:

**Pull request merged**
