### PR TITLE
Remove greedy reestimation of distribution

### LINKED ISSUE #2593: Remove greedy re-estimation of distribution
in Anomaly Likelihood. Turns out this trick can hurt when you have anomalies early on. It does not seem to help in any situation.  Tested and verified with NAB.

### PR DESCRIPTION
**Pull request by subutai**
Turns out this trick can hurt when you have anomalies early on. It does not seem to help in any situation.  Tested and verified with NAB.

Fixes #2593

### CODE REVIEW

**Comment by subutai** [comment]
@vitaly-krugl Interesting finding after lots of experimentation with NAB.

**Comment by cogmission** [comment]
I'm amazed you can change that without having to change a test? *wink*

That isn't a comment on any one person... You guys are my heroes, and I
love NuPIC!

But still indicates that tests may need attention?

On Wed, Sep 23, 2015 at 10:18 AM, Subutai Ahmad <notifications@github.com>
wrote:

> @vitaly-krugl <https://github.com/vitaly-krugl> Interesting finding after
> lots of experimentation with NAB.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/pull/2594#issuecomment-142637027>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by oxtopus** [comment]
@cogmission on it.  We have a very high-level test in https://github.com/numenta/numenta-apps/blob/master/htmengine which is tested in our internal pipelines.  I'm working on a proposal for a similar test in nupic to check for changes in anomaly likelihood results, so it can be tested as part of nupic proper.

**Comment by cogmission** [comment]
Awesome as always, Austin! :-)

:+1:


On Wed, Sep 23, 2015 at 11:07 AM, Austin Marshall <notifications@github.com>
wrote:

> @cogmission <https://github.com/cogmission> on it. We have a very
> high-level test in
> https://github.com/numenta/numenta-apps/blob/master/htmengine which is
> tested in our internal pipelines. I'm working on a proposal for a similar
> test in nupic to check for changes in anomaly likelihood results, so it can
> be tested as part of nupic proper.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/pull/2594#issuecomment-142649780>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by subutai** [comment]
@cogmission Yes, I agree with you. Unfortunately this sort of benchmark performance is not easily tested in a quick running unit test scenario. In addition to what @oxtopus said, I would like us to add NAB to the nightly regression tests (it takes a while to run through all the datasets). I think maintaining our anomaly detection accuracies should be a prerequisite to cutting a release.

**Comment by vitaly-krugl** [comment]
@subutai: regarding
> Interesting finding after lots of experimentation with NAB

That's another reason to expedite integration of this logic into htmengine's ModelRunner.

CC @scottpurdy

**Comment by subutai** [comment]
> That's another reason to expedite integration of this logic into htmengine's ModelRunner.

Agreed - we should be consistent in how we use anomaly likelihood throughout the codebase.  BTW, I should say it's not a massive difference, it's a corner case. It's primarily when you get anomalies soon after the probationary period is over. In a long-running scenario it doesn't make a difference either way.

**Comment by vitaly-krugl** [comment]
It's the consistency that I am after.

**Comment by subutai** [comment]
> It's the consistency that I am after.

Agreed. @vitaly-krugl Are you ok with me merging this change?

**Comment by vitaly-krugl** [comment]
LGTM @subutai

**Pull request merged**
