### PR TITLE
fixed comments

### LINKED ISSUE #1768: Fix up Doxygen tokens in spatial_pooler.py
spatial_pooler.py uses :param instead of @param. This issue is to clean all that up.

### PR DESCRIPTION
**Pull request by epaxon**
Fixes #1768.

@subutai trying again now that the license is signed

### CODE REVIEW

**Comment by rhyolight** [comment]
@epaxon License processing is a manual process, so it will take awhile for Celeste to do it.

**Comment by rhyolight** [comment]
s

**Comment by rhyolight** [comment]
s

**Comment by rhyolight** [comment]
@subutai PR validated.

**Comment by subutai** [comment]
Thanks!

**Comment by subutai** [comment]
@rhyolight Do the doxygen fixes look right?

**Comment by rhyolight** [comment]
:+1:

**Pull request merged**
