### PR TITLE
Change term predictedColumns to predictedActiveColumns in TemporalMemory

### PR DESCRIPTION
**Pull request by chetan51**
Fixes https://github.com/numenta/nupic/issues/2452.

### CODE REVIEW

**Comment by chetan51** [comment]
@sco

**Comment by scottpurdy** [comment]
:+1:

**Comment by cogmission** [comment]
@scottpurdy  @chetan51  I love you guys! Thank you! I don't think there is any other company in existence that is so responsive and respectful of its community! This may look trivial to you guys, but its significance is so subtle it can just zoom by without appreciation. You guys are great!

**Comment by chetan51** [comment]
@cogmission :)

**Comment by rhyolight** [comment]
@cogmission I thought you said nobody listens to you. :stuck_out_tongue_winking_eye:

**Comment by cogmission** [comment]
That was just me pouting... :-)  Besides... I acknowledged everybody a couple of comments up. Did you see that?

**Pull request merged**
