### PR TITLE
DeltaEncoder capnproto implementation

### LINKED ISSUE #1988: Add capnp serialization to DeltaEncoder
See #1715

### PR DESCRIPTION
**Pull request by oxtopus**
Builds off of #1997 and fixes #1988.

### CODE REVIEW

**Comment by rhyolight** [comment]
Something weird happened in Travis. Restarted.

**Comment by scottpurdy** [comment]
Make sure you rebase after upstream branch merges but :+1: from what I can tell.

**Comment by oxtopus** [comment]
Thanks.  Do I really need to rebase?  I don't normally rebase, and haven't needed to for the others.

**Comment by scottpurdy** [comment]
Probably not, I just couldn't tell by looking at the mix of commits what would be left after a merge.

**Comment by oxtopus** [comment]
I figured out the failure.  It's actually failing due to the python interpreter crashing because of a potential bug in either pycapnp or capnproto (see https://github.com/jparyani/pycapnp/issues/59), which is fixed in a later PR (https://github.com/numenta/nupic/pull/2007).  I'm going to close this one and the others and focus on the later one which has some feedback from @scottpurdy

**Pull request closed without merging**
