### PR TITLE
Add capnproto serialization to CLAModel

### PR DESCRIPTION
**Pull request by chetan51**
Fixes https://github.com/numenta/nupic/issues/2889.

### CODE REVIEW

**Comment by chetan51** [comment]
@scottpurdy

**Comment by scottpurdy** [comment]
Please add basic tests to make sure it works and let me know, I'll review then.

**Comment by chetan51** [comment]
@scottpurdy So the way I've been testing is by modifying OPF to call `writeToCheckpoint` instead of `save` and `readFromCheckpoint` instead of `load`, and running the `test_NonTemporalMultiStep` in `opf_checkpoint_test.py`. Is there any way I can check this in without changing the default serialization method for users of OPF?

**Comment by scottpurdy** [comment]
You can test serialization at the CLAModel level or at the OPF level. It sounds like testing at the OPF level doesn't give you and option for which serialization functions to use so you might have to do it at the CLAModel level for now. Either way, if there is an existing test that works then make an additional test that does the same thing except calls the new serialization rather than old.

**Comment by breznak** [comment]
I remember a ML discussion on too large serialized files, can you verify with the new method? Or leave it as a seperate issue?

**Comment by scottpurdy** [comment]
@breznak - There was a question about the serialized state (old method) creating large files. I think the conclusion was that it was expected. The new method will use less space.

**Comment by chetan51** [comment]
@scottpurdy Please see latest commit for the added tests.

**Comment by scottpurdy** [comment]
:+1: after fixing AppVeyor by disabling new test for Windows.

**Pull request merged**
