### PR TITLE
Update hello_tm.py

### LINKED ISSUE #3404: hello_tm.py fails because minThreshold value is higher than activationThreshold
Line 68: I propose to lower `minThreshold` from `10` to `8` so its value is not higher than the `activationThreshold` (set at `8`). 

https://github.com/numenta/nupic/blob/master/examples/tp/hello_tm.py#L68

### PR DESCRIPTION
**Pull request by Containerhouse**
Line 68: Lowered `minThreshold` value to `8` so its value is not higher than `activationThreshold` (also `8`).

fixes #3404

### CODE REVIEW

**Comment by rhyolight** [comment]
@Containerhouse Per our [Developer process](https://github.com/numenta/nupic/wiki/Development-Process), can you please create a new issue defining the problem this PR is fixing?

**Comment by rhyolight** [comment]
@Containerhouse there was a problem with your contributor license. We'll be in touch via email.

**Comment by Containerhouse** [comment]
@rhyolight Just re-signed personally. Waiting for Adobe link to complete process Thanks. -George

**Comment by rhyolight** [comment]
test

**Comment by rhyolight** [comment]
I don't know what is wrong with the "contributor validator" it was working fine last week.

**Pull request merged**
