### PR TITLE
Adding OS X to requirements of audiostream readme.

### LINKED ISSUE #1946: IndexError when python audiostream_tp.py
/home/rdaneel/Envs/kodama_NuPIC_env/local/lib/python2.7/site-packages/pkg_resources/__init__.py:1222: UserWarning: /home/rdaneel/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Number of columns:	512
Max size of input:	51
Sampling rate (Hz):	44100
Passband filter (Hz):	500 - 10000
Passband filter (bin):	46 - 928
Bin difference:		882
Buffersize:		4096
Traceback (most recent call last):
  File "audiostream_tp.py", line 292, in <module>
    audiostream = AudioStream()
  File "audiostream_tp.py", line 211, in __init__
    self.processAudio()
  File "audiostream_tp.py", line 250, in processAudio
    actualInt = self.e.encode(ufs)
  File "/home/rdaneel/Envs/kodama_NuPIC_env/local/lib/python2.7/site-packages/nupic-0.3.0.dev0-py2.7-linux-x86_64.egg/nupic/encoders/base.py", line 138, in encode
    self.encodeIntoArray(inputData, output)
  File "/home/rdaneel/Envs/kodama_NuPIC_env/local/lib/python2.7/site-packages/nupic-0.3.0.dev0-py2.7-linux-x86_64.egg/nupic/encoders/sparse_pass_through_encoder.py", line 54, in encodeIntoArray
    denseInput[input] = 1
IndexError: arrays used as indices must be of integer (or boolean) type

### LINKED ISSUE #1955: Mark audiostream example as OS X only for now
Less confusing for linux users.

### PR DESCRIPTION
**Pull request by rhyolight**
Fixes #1955.

### CODE REVIEW

**Comment by rhyolight** [comment]
@oxtopus ?

**Comment by breznak** [comment]
:cry: can we rather make it work for us on linux too? :smile: I think I remember this worked on Linux in the past (?)

I needed to `sudo apt-get install python-audio` + some stuff to get `jack` working. 

But I'm getting this error (looks like really err in Encoder??)

```
(pyenv)mmm@mmm-U2442:~/devel/nupic/nupic-source$ python examples/audiostream/audiostream_tp.py 
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
Number of columns:      512
Max size of input:      51
Sampling rate (Hz):     44100
Passband filter (Hz):   500 - 10000
Passband filter (bin):  46 - 928
Bin difference:         882
Buffersize:             4096
[   0.            0.58049887    1.74149656    8.70748329   11.02947807
   12.19047642   12.77097511   13.35147381   13.9319725    15.09297085
   16.83446693   17.99546432   33.08843613   34.82993317   35.99092865
   37.15192795   37.73242569   38.89342499   39.47392273   40.05442047
   40.63492203   41.79591751   42.37641907   44.11791229   44.69841385
   48.76190567   49.34240341   49.92290115   51.08390045   52.24489975
   52.82539749   60.37188339   61.53287888   62.11338043   62.69387817
   63.27437592   71.40135956   73.72335815   74.88435364   77.78684998
   78.36734772   87.65532684   88.81632996   93.46031952   94.04081726
   94.621315    177.05215454  196.78910828  197.95011902  222.91156006
  322.17687988] <type 'numpy.ndarray'>
Traceback (most recent call last):
  File "examples/audiostream/audiostream_tp.py", line 299, in <module>
    audiostream = AudioStream()
  File "examples/audiostream/audiostream_tp.py", line 214, in __init__
    self.processAudio()
  File "examples/audiostream/audiostream_tp.py", line 255, in processAudio
    actualInt = self.e.encode(ufs)
  File "/home/mmm/devel/nupic/nupic-source/nupic/encoders/base.py", line 133, in encode
    self.encodeIntoArray(inputData, output)
  File "/home/mmm/devel/nupic/nupic-source/nupic/encoders/sparse_pass_through_encoder.py", line 54, in encodeIntoArray
    denseInput[input] = 1
IndexError: arrays used as indices must be of integer (or boolean) type
```

for 

```
diff --git a/examples/audiostream/audiostream_tp.py b/examples/audiostream/audiostream_tp.py
index 03299b2..4dc16c1 100755
--- a/examples/audiostream/audiostream_tp.py
+++ b/examples/audiostream/audiostream_tp.py
@@ -250,6 +250,8 @@ class AudioStream:
     fs = numpy.sort(ys.argsort()[-self.numInput:])
     rfs = fs.astype(numpy.float32) / (self.lowpass - self.highpass) * self.numCols
     ufs = numpy.unique(rfs)
+    assert (ufs is not None and ufs >=0).all()
+    print ufs, type(ufs)
     actualInt = self.e.encode(ufs)
     actual = actualInt.astype(numpy.float32)
```

**Comment by rhyolight** [comment]
Ok, I didn't think this ever worked on Linux. I'd be happy to accept a PR that made it work instead of this PR.

**Comment by breznak** [comment]
agreed. let's not delay this, please merge and let's open an issue to make
it work on Linux
(my appologies, but I thought I've really played nupic+midi already - maybe
from the song learning CLA hackathlon contrib?)

**Comment by rhyolight** [comment]
I'm going to merge this, as it's just a readme change.

**Pull request merged**
