### PR TITLE
Encoders inherit more from Encoder() class

### LINKED ISSUE #544: Log Encoder should be a subclass of Scalar Encoder
The current class tightly wraps the Scalar Encoder passing on all inputs after a math.log10() transformation. It would be cleaner (by removing duplicate logic) to subclass Scalar Encoder.

### LINKED ISSUE #947: Refactor common logic in encoders to base class
I see duplicate logic in various encoders, especially in their `init` functions. For example, setting `n` and `w` and enforcing good values for them. Also setting the `name`. Common logic should be refactored to the respective base classes.

### LINKED ISSUE #981: Clear output vector before passing to encoder
When RecordSensor calls `encoder.encodeIntoArray`, it reuses a numpy array for the `output` vector, but doesn't clear it. When writing an encoder, if you forget to clear it before using it, you can get unexpected results.

Here are 3 ways to resolve this:
1. Make RecordSensor clear it before passing it to the encoder.
2. Make the base encoder have a method that gets called before encodeIntoArray, that can be overridden.
3. Make it clear that every encoder needs to clear the vector before using it.

### PR DESCRIPTION
**Pull request by breznak**
refactors encoders to share more common fields and methods in parent `base.Encoder` class. 
Should simplify creation of a new encoder, and assertion tests share more common paths, so better testing (for tests :) )
I'd like to get this done before I start on reimplementation in c++ https://github.com/numenta/nupic.core/issues/62

fixes #544 
fixes #981 
fixes #947

### CODE REVIEW

**Comment by rhyolight** [comment]
s

**Comment by breznak** [comment]
@rhyolight I cant get to the CI results...?

**Comment by rhyolight** [comment]
@breznak Really? Maybe it was a temporary Travis problem, because I can see them even when I'm not logged into Travis-CI. Are you still having problems?

**Comment by breznak** [comment]
@rhyolight my bad, some plugin was blocking the JS needed by travis. thank you

**Comment by breznak** [comment]
@rhyolight could you help me pin-point the config where encoder is setup in this experiment? 
https://travis-ci.org/numenta/nupic/jobs/50289126#L3708

**Comment by rhyolight** [comment]
@breznak I'm not certain where that is. But... [this is the experiment that's failing](https://github.com/numenta/nupic/blob/master/tests/integration/nupic/opf/opf_experiment_results_test.py#L110..L116):

      # For this one, in theory the error for 1 step should be < 0.20
      { 'experimentDir': 'experiments/multistep/simple_0',
        'results': {
          ('DefaultTask.TemporalMultiStep.predictionLog.csv',
           "multiStepBestPredictions:multiStep:errorMetric='avg_err':steps=1:window=200:field=field1"):
                    (0.0, 0.20),
        }
      },

[This is the description.py being used from `./examples/opf/experiments/multistep/simple_0/description.py`](https://github.com/numenta/nupic/blob/master/examples/opf/experiments/multistep/simple_0/description.py):

```
import os
from nupic.frameworks.opf.expdescriptionhelpers import importBaseDescription

# the sub-experiment configuration
config = \
{
  'dataSource': 'file://' + os.path.join(os.path.dirname(__file__),
                                         '../datasets/simple_0.csv'),
  'modelParams': { 'clParams': { },
                   'sensorParams': { 'encoders': { }, 'verbosity': 0},
                   'spParams': { },
                   'tpParams': { }}}

mod = importBaseDescription('../base/description.py', config)
locals().update(mod.__dict__)
```

**Comment by breznak** [comment]
I don't know what's wrong with that test :disappointed: It uses SDRCategoryEnc and ScalarEnc, I tried: 
* replacing the SDRCategory with implementation from master (same err), replacing Scalar is not that easy, so I did not try that. 
* when I disable this one test `tests/integration/nupic/opf/opf_experiment_results_test.py` all other unit + integration tests pass.

**Comment by breznak** [comment]
closing, the development derived too much in the meanwhile, and I dont have time for this now.

**Pull request closed without merging**
