### PR TITLE
Remove TestNode from nupic in favor of the one in nupic.core

### PR DESCRIPTION
**Pull request by chetan51**
Fixes https://github.com/numenta/nupic/issues/2710.

### CODE REVIEW

**Comment by chetan51** [comment]
@scottpurdy

**Comment by scottpurdy** [comment]
Can you update the test to validate the new fields?

**Comment by chetan51** [comment]
@scottpurdy Which test? I've updated the test in nupic.core [1].

[1] https://github.com/numenta/nupic.core/pull/676

**Comment by chetan51** [comment]
@scottpurdy Bump

**Comment by scottpurdy** [comment]
@chetan51 - So there aren't tests for this version? Can we just remove this version in favor of version in nupic.bindings?

**Comment by chetan51** [comment]
@scottpurdy Done.

**Pull request merged**
