### PR TITLE
Initial appveyor setup and build test.

### LINKED ISSUE #1888: Create NuPIC Appveyor configuration for Windows builds
Depends on https://github.com/numenta/nupic.core/issues/311

NuPIC Appveyor build downloads and uses win64 nupic.core binaries.

### PR DESCRIPTION
**Pull request by rhyolight**
This PR is just to get builds running in AppVeyor. When I'm satisfied, I'll create another PR with squashed changes for #1888.

cc @rcrowder

### CODE REVIEW

**Comment by rhyolight** [comment]
Watching https://ci.appveyor.com/project/numenta-ci/nupic/build/0.0.1.2

**Comment by rhyolight** [comment]
Watching https://ci.appveyor.com/project/numenta-ci/nupic/build/0.0.1.3

**Comment by rhyolight** [comment]
https://ci.appveyor.com/project/numenta-ci/nupic/build/0.0.1.4

**Comment by rhyolight** [comment]
Better yet, just watch here: https://ci.appveyor.com/project/numenta-ci/nupic/history

**Comment by rhyolight** [comment]
Got past installing numpy. Now dealing with issues in `setup.py`...

**Comment by david-ragazzi** [comment]
Matt, to avoid re-work, you can use my setup.py in my windows build branch. Unfortunately as already said by Richard, nupic will compile only with GCC. The good news is that nupic.core is building well under gcc and windows even in VS (you need specificy the native compilers at CMake command line). So you can publish the nupic.core binaries in gcc and dowload them from nupic.

**Comment by david-ragazzi** [comment]
The problem with VC++ is that it has not support to some c++11 features used by pycapn in nupic.

**Comment by rhyolight** [comment]
Thanks @david-ragazzi that is helpful. I'm looking at your version of `setup.py` right now and working through it.

**Comment by rhyolight** [comment]
Running into this problem: http://stackoverflow.com/questions/15149125/windows-error-in-os-listdir

**Comment by rhyolight** [comment]
Blocked on https://github.com/numenta/nupic.core/issues/404.

**Comment by rhyolight** [comment]
[current error](https://ci.appveyor.com/project/numenta-ci/nupic/build/0.0.1.44#L2174):

```
c:\python27-x64\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION 
C:\projects\nupic\extensions\core\build\release\include\nupic/types/Types.h(35) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory 
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
Command exited with code 1
```

**Comment by rhyolight** [comment]
So https://github.com/numenta/nupic.core/blob/master/src/nupic/types/Types.h#L35 is broken because `stdint.h` is missing in the C++ environment. 

Relavent? http://stackoverflow.com/questions/12970293/why-microsoft-visual-studio-cannot-find-stdint-h

I need help. @rcrowder @david-ragazzi @breznak @utensil

**Comment by rcrowder** [comment]
Drop numpy from your requirements Takes **ages** to build. Get back to that later. A 64 bit superpack can be found or created to install large libraries such as numpy. You may also need need to trick the build system to use a different version of the compiler (for now, shift to clang expected for CI builds later) - Yaml line [1] Resulting build [2] Cap'n Proto may have a 64 bit wheel available soon? 

stdint.h has been in since 2010 [3], we compile the core library with 2015 hence the set VS90... trick [1]

CMD_IN_ENV needs updating to target the same VM OS as AppVeyor (Windows Server 2012 I believe), looks like it sets up for 2008.

1 https://github.com/rcrowder/nupic/blob/1786-windows-build/appveyor.yml#L55
2 https://ci.appveyor.com/project/rcrowder/nupic/build/1.0.34
3 http://stackoverflow.com/questions/126279/c99-stdint-h-header-and-ms-visual-studio?rq=1

**Comment by rhyolight** [comment]
> Drop numpy from your requirements Takes ages to build.

I agree, but I can't do a build without it. I have no choice. NuPIC requires numpy to build. 

Otherwise, thanks for the advice, I'll get to it.

**Comment by rcrowder** [comment]
PS: The [1] set VS90 trick must be **just before** the NuPIC build.

**Comment by rhyolight** [comment]
> CMD_IN_ENV needs updating to target the same VM OS as AppVeyor (Windows Server 2012 I believe), looks like it sets up for 2008.

I'm not sure how to do that. I did add the line to attempt to trick python to use the right compiler though. Watching https://ci.appveyor.com/project/numenta-ci/nupic/build/0.0.1.65...

**Comment by rhyolight** [comment]
Now the OS X build is failing on this PR and I don't know why. It has failed a couple times now for different reasons. :confused: 

https://travis-ci.org/numenta/nupic/builds/58499954

**Comment by david-ragazzi** [comment]
@rhyolight I didn't have problems to install python, pip and numpy in my local machine. I simply downloaded and run https://www.python.org/ftp/python/2.7.6/python-2.7.6.amd64.msi . We could do this using `/quiet` mode.

**Comment by rhyolight** [comment]
@david-ragazzi I'm not having problems with python, pip, or numpy. I'm having problems with missing `stdint.h`.

**Comment by rhyolight** [comment]
@rcrowder said:
> A 64 bit superpack can be found or created to install large libraries such as numpy.

Like this? http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy

**Comment by rcrowder** [comment]
Exactly that web site. Plus that NumPY has Intel Math Kernel Library built
in :) As myself discovered, and maybe David, there are build limits on
AppVeyor (40 mins total for free OSS projects?), which kind of forces big
Python libraries to be installed via a superpack.

Key change is to the CMD_IN_ENV? function, and making sure that it is at
least 2010 so that stdint.h is included. Or stick with 2008 and
boost::stdint header, but then 2008 compilers won't cope with C++11
language features.

**Comment by rhyolight** [comment]
> Key change is to the CMD_IN_ENV? function, and making sure that it is at
> least 2010 so that stdint.h is included.

Yes, that's what I'd like to do, but CMD_IN_ENV is all Greek to me. I don't see what I need to update.

**Comment by rhyolight** [comment]
PS: I'm not a Greek.

**Comment by rcrowder** [comment]
It's a tricky task. Here's more info for your noggin;
https://github.com/cython/cython/wiki/CythonExtensionsOnWindows

**Comment by rhyolight** [comment]
Closing cause I know I won't be able to finish this soon. See my work here: https://github.com/rhyolight/nupic/tree/add-appveyor.

**Comment by rcrowder** [comment]
It makes sense, this is a challenging issue. We can chat more at the Hackathon, but still keen to find time to investigate the use of Cython and Clang.

**Pull request closed without merging**
