### PR TITLE
Removed dead code from nupic/research

### PR DESCRIPTION
**Pull request by david-ragazzi**
Fixes https://github.com/numenta/nupic/issues/1857

### CODE REVIEW

**Comment by breznak** [comment]
:+1: 
@rhyolight please restart https://travis-ci.org/numenta/nupic/jobs/51907761

**Comment by rhyolight** [comment]
Restarted. Travis had several OS X MySQL download failures.

**Comment by rhyolight** [comment]
@subutai @scottpurdy Please approve before removal.

**Comment by subutai** [comment]
:+1: as long as tests pass. Would be good if @scottpurdy also checks these to be sure.

**Comment by scottpurdy** [comment]
Thanks for digging these up David!

- The anomalyzer was a simple tool for generating data to test anomaly detection. I think it is still useful and should be kept.
- The data generation tool is much older and hasn't been used recently. There were a couple bugs that had developed but I was able to fix them easily. I am going to send a PR to get it working. The visualization is a nice idea but crudely implemented. So it isn't clear to me if it will be useful or not but I'd like to have a few people play with it before we decide.
- The ObjDiff and TrainingHooks files can be removed.

**Comment by david-ragazzi** [comment]
Ok, in either case, as they are not affected by serialization I'll fix `anomalyzer` and `data generation tool` file names (to snake_case) and move them into `nupic/algorithms`.

**Comment by scottpurdy** [comment]
@david-ragazzi - I have a branch, will send in a sec.

**Comment by david-ragazzi** [comment]
@scottpurdy I discard the changes for `anomalizer` and `data_generator`. Could merge it?

**Comment by scottpurdy** [comment]
:+1: waiting for :green_apple:

**Comment by david-ragazzi** [comment]
> :+1: waiting for :green_apple:

Green.

**Pull request merged**
