### PR TITLE
NuPIC visualizations

### PR DESCRIPTION
**Pull request by breznak**
a web UI tool for visualizations of NuPIC results (OPF experiment results, generic CSV files, NAB). 

Allows interactive modifications what fields to show, zooming, etc. 
Please see `scripts/visualizations/README` for howto run & test it out. 

KUDOs to @jefffohl for this work!! :clap: 

Fixes: #2658

### CODE REVIEW

**Comment by rhyolight** [comment]
@scottpurdy This provides a useful graphing functionality for NuPIC output. For example, here is the NYC taxi data in NAB:

screen shot 2015-11-05 at 3 57 04 pm

As I mentioned to @breznak and @jefffohl, if this toolset continues to evolve, I believe it should be placed in an external repository so it can be run in CI with unit tests of its own. But for this initial push, I say :+1:. Are you okay with a merge?

**Comment by scottpurdy** [comment]
@rhyolight - It seems to me that putting this in the main repo will just slow down development. Why not have a separate repo where the author can do whatever they want?

**Comment by rhyolight** [comment]
@scottpurdy I think you're right. 

Hey @breznak @jefffohl, why not just make this its own repo right now and put all web-based visualization logic there? We could put it in https://github.com/nupic-community/nupic.visualizations.

**Comment by jefffohl** [comment]
I am fine with that. Should I make the repo?

**Comment by rhyolight** [comment]
Go for it!

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by jefffohl** [comment]
What license do you recommend? GNU Affero?

**Comment by rhyolight** [comment]
I think MIT will be fine because it does not depend upon NuPIC at all.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by jefffohl** [comment]
@rhyolight - great thanks.

**Comment by jefffohl** [comment]
Here it is: https://github.com/nupic-community/nupic.visualizations

Hopefully, this does not present too big a problem for @breznak. If it does, we can delete the repo and start over.

We should probably delete nupic/scripts/visualization directory from NuPIC at this point.

**Comment by breznak** [comment]
@jefffohl no problem! :+1: closing this PR. 
I'll just squash the commits and base them off of the new repo.

**Comment by jefffohl** [comment]
@breznak - one thing to note, and I hope it doesn't cause any problems for you - is that in the new repository, I changed the name of `opf_visualizer.js` and `opf_visualizer.css` to `nupic_visualizer.js` and nupic_visualizer.css`

**Comment by rhyolight** [comment]
Great job all. I think you'll find you have much more flexibility to
experiment in this new repository. Please keep us up-to-date on your
projects. Demos welcome!

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Pull request closed without merging**
